import {expect,test} from "@playwright/test";
import {stubAuthenticatedSession} from "./helpers";

test("calendar supports media review approval auto-post and manual publish",async({page})=>{
 await stubAuthenticatedSession(page);let posts:any[]=[];let published=false;
 await page.route("**/api/calendar",async route=>{const req=route.request();if(req.method()==="GET")return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({posts})});if(req.method()==="POST"){const input=await req.postDataJSON(),post={id:"post-1",...input};posts=[post];return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({post})});}return route.continue();});
 await page.route("**/api/calendar/post-1",async route=>{const req=route.request();if(req.method()==="PATCH"){const input=await req.postDataJSON();posts=posts.map(p=>p.id==="post-1"?{...p,...input}:p);return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({post:posts[0]})});}if(req.method()==="DELETE"){posts=[];return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({ok:true})});}return route.continue();});
 await page.route("**/api/calendar/post-1/publish",async route=>{published=true;posts=posts.map(p=>({...p,status:"published",publishedAt:new Date().toISOString()}));return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({ok:true})});});
 await page.goto("/calendar");await expect(page.getByRole("heading",{name:"Content Calendar"})).toBeVisible();await page.getByRole("button",{name:"Add post",exact:true}).click();await page.getByLabel("Title").fill("Generated campaign image");await page.getByLabel("Format").selectOption("image");await page.getByLabel("Network").selectOption("instagram");await page.getByLabel("Status").selectOption("pending");await page.getByLabel("Caption / article notes").fill("Owner review copy");await page.getByRole("button",{name:"Save",exact:true}).click();
 posts=posts.map(p=>({...p,mediaUrl:"/generated/test.png",mediaType:"image/png"}));await page.reload();await expect(page.getByText("Generated campaign image").first()).toBeVisible();await page.getByRole("button",{name:"Approve"}).click();await expect(page.getByText("approved").first()).toBeVisible();await page.getByRole("button",{name:"Enable auto"}).click();await expect(page.getByRole("button",{name:"Disable auto"})).toBeVisible();await page.getByRole("button",{name:"Post now"}).click();await expect.poll(()=>published).toBe(true);await expect(page.getByText("published").first()).toBeVisible();await expect(page.getByRole("button",{name:"Post now"})).toHaveCount(0);
});
