import { expect, test, type Page, type Route } from "@playwright/test";
import { stubAuthenticatedSession } from "./helpers";

const ONE_PIXEL_PNG="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z9ZkAAAAASUVORK5CYII=";
const plan={mission:"Explain why documenting a collision scene matters before evidence disappears.",subject:"Professional spokesperson beside a safely parked vehicle, eye-level camera, calm direct delivery.",script:"Before you leave the scene, document what you can safely preserve.",hook:"Document it now",caption:"A few careful steps can preserve useful information after a collision.",visualDirection:"One clear roadside concept that works as a strong frame or simple motion shot.",rationale:"Simple action-oriented guidance fits social content."};
async function stubBase(page:Page){
  await stubAuthenticatedSession(page);await page.route("**/api/admin/settings",(route:Route)=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({defaultProvider:"veo",providers:{veo:{keyConfigured:true},grok:{keyConfigured:true},a2e:{keyConfigured:true},hedra:{keyConfigured:true}}})}));
  await page.route("**/api/admin/avatars",(route:Route)=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({avatars:[{id:"female-anchor-01",name:"Female Anchor 01",referenceImage:"/avatars/female-anchor-01/identity.png",wardrobeRegenerationPrompt:null,views:{front:{status:"ready"}}}]})}));
  await page.route("**/api/admin/avatars/female-anchor-01/asset?view=front",(route:Route)=>route.fulfill({status:200,contentType:"image/png",body:Buffer.from(ONE_PIXEL_PNG,"base64")}));
  await page.route("**/api/internal/campaign-plan",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({plan})}));
}

test("Create is the single campaign builder and AI plans campaign/output/provider changes",async({page})=>{await stubBase(page);let plans:any[]=[];await page.unroute("**/api/internal/campaign-plan");await page.route("**/api/internal/campaign-plan",async route=>{plans.push(await route.request().postDataJSON());return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({plan})})});await page.goto("/");await expect(page.getByRole("heading",{name:"Create"})).toBeVisible();await expect(page.getByText("Campaign setup")).toBeVisible();await expect(page.getByRole("button",{name:/Video Generate video posts/i})).toBeVisible();await expect(page.getByRole("button",{name:/Still image Generate a campaign still/i})).toBeVisible();await expect(page.getByRole("button",{name:/Auto mix Alternates Video/i})).toBeVisible();await page.getByRole("button",{name:/Still image Generate a campaign still/i}).click();await expect.poll(()=>plans.some(p=>p.outputMode==="image")).toBeTruthy();await expect(page.getByText("Video engine")).toHaveCount(0);await page.getByRole("button",{name:/Auto mix Alternates Video/i}).click();await expect(page.getByText(/Auto mix next output: Video/)).toBeVisible();await expect(page.getByText("Video engine")).toBeVisible();});

test("Create blocks campaign-unsafe identity reference and loads canonical front",async({page})=>{await stubBase(page);await page.goto("/");await page.getByLabel("Choose canonical avatar").selectOption("female-anchor-01");await expect(page.getByText("Loaded campaign-safe identity for Female Anchor 01.")).toBeVisible();await expect(page.getByText(/Using: female-anchor-01-front\.png/)).toBeVisible();});

test("Still generation lands in media workflow and can publish to Instagram",async({page})=>{await stubBase(page);let ig:any=null;await page.route("**/api/internal/campaign-image",route=>route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({assetId:"img-1",assetUrl:"/generated/images/img-1.png",model:"black-forest-labs/flux.1-schnell",mimeType:"image/png"})}));await page.route("**/generated/images/img-1.png",route=>route.fulfill({status:200,contentType:"image/png",body:Buffer.from(ONE_PIXEL_PNG,"base64")}));await page.route("**/api/publish/instagram",async route=>{ig=await route.request().postDataJSON();return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({ok:true})})});await page.goto("/");await page.getByRole("button",{name:/Still image Generate a campaign still/i}).click();await page.getByRole("button",{name:"Generate still image"}).click();await expect(page.getByAltText("Generated campaign still")).toBeVisible();await expect(page.getByText(/Automatically added to Library \+ Calendar/)).toBeVisible();page.on("dialog",d=>d.accept());await page.getByRole("button",{name:"Post to Instagram now"}).click();expect(ig.mediaUrl).toBe("/generated/images/img-1.png");expect(ig.mediaType).toBe("image/png");});

test("Auto mix flips Generate now and saves alternating Calendar plan",async({page})=>{await stubBase(page);let campaignPayload:any=null;await page.route("**/api/internal/generate",route=>route.fulfill({status:202,contentType:"application/json",body:JSON.stringify({job:{id:"job-create",status:"running"}})}));await page.route("**/api/v1/video/job-create",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({id:"job-create",status:"succeeded",fileUrl:"/api/v1/video/job-create/file"})}));await page.route("**/api/v1/video/job-create/file",route=>route.fulfill({status:200,contentType:"video/mp4",body:""}));await page.route("**/api/internal/campaign-image",route=>route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({assetId:"img-2",assetUrl:"/generated/images/img-2.png",model:"flux",mimeType:"image/png"})}));await page.route("**/generated/images/img-2.png",route=>route.fulfill({status:200,contentType:"image/png",body:Buffer.from(ONE_PIXEL_PNG,"base64")}));await page.route("**/api/campaigns",async route=>{campaignPayload=await route.request().postDataJSON();return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({campaign:{id:"c1"},calendarCount:14})})});await page.goto("/");await page.getByRole("button",{name:/Auto mix Alternates Video/i}).click();await page.getByLabel("Campaign name").fill("Mixed PI campaign");await page.getByLabel("Fill Calendar for").selectOption("14");await page.getByRole("button",{name:"Generate next · Video"}).click();await expect(page.getByRole("button",{name:"Generate next · Still image"})).toBeVisible({timeout:10000});await page.getByRole("button",{name:"Generate next · Still image"}).click();await expect(page.getByRole("button",{name:"Generate next · Video"})).toBeVisible();await page.getByRole("button",{name:"Save campaign + fill Calendar"}).click();await expect(page.getByText(/14 Calendar slots created/)).toBeVisible();expect(campaignPayload.outputMode).toBe("auto_mix");expect(campaignPayload.planningHorizonDays).toBe(14);});

test("Create podcast mode persists split-screen surface on Save campaign",async({page})=>{
  await stubBase(page);
  let campaignPayload:any=null;
  await page.route("**/api/campaigns",async route=>{campaignPayload=await route.request().postDataJSON();return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({campaign:{id:"split-1"},calendarCount:7})})});
  await page.goto("/");
  await page.getByLabel("Content format").selectOption("podcast");
  await expect(page.getByText("Split-screen surface")).toBeVisible();
  await expect(page.getByText("Document it now")).toBeVisible();
  await page.getByLabel("Split relationship").selectOption("question_answer");
  await page.getByLabel("Upper AI engine").selectOption("veo");
  await page.getByLabel("Split-screen frame template").selectOption("office-warm");
  await page.getByLabel("Campaign name").fill("Split surface campaign");
  await expect(page.getByRole("link",{name:"Continue to two-lane production",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Save campaign + fill Calendar"}).click();
  await expect(page.getByText(/7 Calendar slots created/)).toBeVisible();
  expect(campaignPayload.contentType).toBe("podcast");
  expect(campaignPayload.splitRelationship).toBe("question_answer");
  expect(campaignPayload.splitTemplate).toBe("office-warm");
  expect(campaignPayload.upperProvider).toBe("veo");
  expect(campaignPayload.videoProvider).toBe("veo");
});
