import { expect, test, type Locator, type Page } from "@playwright/test";

async function realLogin(page:Page){await page.goto("/login");await page.getByPlaceholder("Admin password").fill(process.env.ADMIN_PASSWORD||"e2e-local-only");await page.getByRole("button",{name:"Sign in"}).click();await expect(page.getByRole("heading",{name:"Create"})).toBeVisible({timeout:15000})}
function field(page:Page,label:string):Locator{return page.locator("label").filter({hasText:new RegExp(`^${label}`)})}function fieldInput(page:Page,label:string){return field(page,label).locator("input")}function fieldSelect(page:Page,label:string){return field(page,label).locator("select")}function fieldTextarea(page:Page,label:string){return field(page,label).locator("textarea")}
async function sameOriginJson(page:Page,url:string){return page.evaluate(async url=>{const r=await fetch(url,{cache:"no-store"});return{status:r.status,body:await r.json()}},url)}

test("real admin workflow persists researched Site and Calendar article through real app routes",async({page})=>{
  await realLogin(page);const suffix=Date.now(),siteName=`E2E Editorial ${suffix}`,siteUrl=`https://e2e-${suffix}.example.com`,articleTitle=`E2E article ${suffix}`;
  await page.route("**/api/sites/research",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({research:{siteName,language:"en",targetAudience:"People researching practical legal information",brandVoice:"clear and authoritative",topicFocus:"educational legal topics",keywords:"legal guide, practical steps",articleLength:"long",cadence:"weekly",cta:"Request a consultation",internalLinking:true,externalLinks:true,imageStyle:"editorial photography",imageAspectRatio:"16:9",cms:"custom",summary:"External crawl/AI boundary stubbed; persistence below is real.",pagesAnalyzed:[siteUrl]}})}));
  await page.goto("/sites");await page.getByRole("button",{name:"Add site",exact:true}).click();await page.getByRole("textbox",{name:"Website URL",exact:true}).fill(siteUrl);await page.getByRole("button",{name:"Research site with AI"}).click();await expect(page.getByRole("textbox",{name:/Target audience/})).toHaveValue(/People researching/);await page.getByRole("button",{name:"Save site",exact:true}).click();await expect(page.getByText(/Install header code/i)).toBeVisible();await expect(page.locator("pre")).toContainText("/api/sites/bridge.js?key=ve_site_");await page.getByRole("button",{name:"Close",exact:true}).last().click();await expect(page.getByText(siteName)).toBeVisible();
  await page.goto("/calendar");await page.getByRole("button",{name:"Add post",exact:true}).click();await fieldInput(page,"Title").fill(articleTitle);await fieldSelect(page,"Format").selectOption("blog");await fieldSelect(page,"Network").selectOption("website");await fieldTextarea(page,"Caption / excerpt / review notes").fill("Owner review excerpt.");await fieldInput(page,"SEO title").fill("E2E SEO title");await fieldInput(page,"Focus keyword").fill("e2e editorial test");await fieldInput(page,"Slug").fill(`e2e-article-${suffix}`);await fieldTextarea(page,"Meta description").fill("A deterministic integration article used to verify the real Calendar persistence workflow.");await fieldTextarea(page,"Article body").fill("## Integration article\n\nThis is persisted through the real Calendar API and SQLite database during CI.\n\n- Reviewable\n- Editable\n- Approval controlled");await page.getByRole("button",{name:"Save",exact:true}).click();
  await expect(page.getByText(articleTitle).first()).toBeVisible();const queueItem=page.locator("article").filter({hasText:articleTitle});await queueItem.getByRole("button",{name:"Approve",exact:true}).click();await expect(page.locator("article").filter({hasText:articleTitle})).toContainText("approved");await page.reload();await expect(page.getByText(articleTitle).first()).toBeVisible();await page.getByText(articleTitle).first().click();await expect(fieldTextarea(page,"Article body")).toHaveValue(/Integration article/);await page.getByRole("button",{name:"Cancel",exact:true}).click();
  await page.goto("/sites");const siteCard=page.locator("section").filter({hasText:siteName});page.once("dialog",d=>d.accept());await siteCard.getByRole("button",{name:`Remove ${siteName}`,exact:true}).click();await expect(page.getByText(siteName)).toHaveCount(0);
});

test("real Create persists Auto mix as alternating Calendar slots",async({page})=>{
  await realLogin(page);const suffix=Date.now(),name=`E2E Mixed ${suffix}`;const plan={mission:"Create practical collision-awareness content.",subject:"Professional adult spokesperson in a believable roadside setting.",script:"Document what you safely can.",hook:"Preserve the details",caption:"Practical next steps after a collision.",visualDirection:"One reusable campaign concept.",rationale:"Works as video and still."};
  await page.route("**/api/internal/campaign-plan",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({plan})}));
  await page.goto("/");await page.getByLabel("Campaign name").fill(name);await page.getByRole("button",{name:/Auto mix Alternates Video/i}).click();await page.getByLabel("Fill Calendar for").selectOption("3");await page.getByRole("button",{name:"Save campaign + fill Calendar"}).click();await expect(page.getByText(/3 Calendar slots created/)).toBeVisible();
  const campaignsResponse=await sameOriginJson(page,"/api/campaigns");expect(campaignsResponse.status).toBe(200);const campaign=campaignsResponse.body.campaigns.find((c:any)=>c.name===name);expect(campaign).toBeTruthy();expect(campaign.outputMode).toBe("auto_mix");
  const calendarResponse=await sameOriginJson(page,"/api/calendar");expect(calendarResponse.status).toBe(200);const slots=calendarResponse.body.posts.filter((p:any)=>p.campaignId===campaign.id).sort((a:any,b:any)=>new Date(a.scheduledAt).getTime()-new Date(b.scheduledAt).getTime());expect(slots).toHaveLength(3);expect(slots.map((p:any)=>p.contentType)).toEqual(["cinematic","image","cinematic"]);expect(slots.every((p:any)=>p.generationStatus==="pending")).toBeTruthy();
});

test("real split-screen composition endpoint persists final media into Library and Calendar",async({page})=>{
  await realLogin(page);const suffix=Date.now(),title=`E2E Split ${suffix}`;
  const response=await page.evaluate(async({title})=>{const form=new FormData();form.append("file",new File([new Uint8Array([26,69,223,163,1,2,3,4])],"composition.webm",{type:"video/webm"}));form.append("title",title);form.append("caption","Rendered two-lane acceptance composition");form.append("upperSource","upper-job-e2e");form.append("lowerSource","lower-job-e2e");form.append("splitPercent","35");const r=await fetch("/api/internal/compositions",{method:"POST",body:form});return{status:r.status,body:await r.json()}},{title});
  expect(response.status).toBe(201);expect(response.body.url).toMatch(/^\/generated\/compositions\/.+\.webm$/);
  const libraryResponse=await sameOriginJson(page,"/api/library");expect(libraryResponse.status).toBe(200);const asset=libraryResponse.body.assets.find((a:any)=>a.title===title);expect(asset).toBeTruthy();expect(asset.kind).toBe("composition");expect(asset.mediaType).toBe("video");expect(asset.label).toContain("35% top");
  const calendarResponse=await sameOriginJson(page,"/api/calendar");expect(calendarResponse.status).toBe(200);const post=calendarResponse.body.posts.find((p:any)=>p.title===title);expect(post).toBeTruthy();expect(post.contentType).toBe("podcast");expect(post.mediaUrl).toBe(response.body.url);expect(post.videoJobId).toBeFalsy();
});
