import { expect, test } from "@playwright/test";
import { stubAuthenticatedSession } from "./helpers";

const imageProviders=[
  {id:"nvidia",label:"NVIDIA FLUX.2 Klein 4B",envVar:"NVIDIA_API_KEY",help:"Fresh portraits only on hosted endpoint.",models:["black-forest-labs/flux.2-klein-4b"],supportsTurnaround:false},
  {id:"gemini",label:"Google Gemini image generation",envVar:"GEMINI_API_KEY",help:"Reference editing.",models:["gemini-2.5-flash-image"],supportsTurnaround:true},
  {id:"openai",label:"OpenAI image generation",envVar:"OPENAI_API_KEY",help:"Reference editing.",models:["gpt-image-1"],supportsTurnaround:true},
  {id:"xai",label:"xAI Grok Imagine",envVar:"XAI_API_KEY",help:"Fresh portraits only.",models:["grok-imagine-image"],supportsTurnaround:false}
];
const plan={mission:"Explain one useful post-collision step.",subject:"Professional spokesperson in one coherent shot.",script:"",hook:"Know the next step",caption:"Practical collision guidance.",visualDirection:"Simple direct visual.",rationale:"Fits the selected format."};
const BASE_APIS=async(page:import("@playwright/test").Page)=>{await stubAuthenticatedSession(page);await page.route("**/api/admin/settings",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({defaultProvider:"veo",providers:{veo:{keyConfigured:true},grok:{keyConfigured:true},a2e:{keyConfigured:true},hedra:{keyConfigured:true}}})}));await page.route("**/api/admin/avatars",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({avatars:[{id:"female-anchor-01",name:"Female Anchor 01",referenceImage:"x",wardrobeRegenerationPrompt:null,views:{front:{status:"ready"}}}]})}));await page.route("**/api/admin/avatars/image-settings",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,provider:"gemini",model:"gemini-2.5-flash-image",providers:imageProviders,modelChoices:["gemini-2.5-flash-image"]})}));await page.route("**/api/internal/campaign-plan",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({plan})}));await page.route("**/api/sites",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({sites:[]})}));await page.route("**/api/library",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({assets:[]})}));await page.route("**/api/calendar",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({posts:[]})}));await page.route("**/api/campaigns",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({campaigns:[]})}));};
function rgb(value:string):[number,number,number]{const nums=value.match(/\d+(?:\.\d+)?/g)?.map(Number)||[0,0,0];return[nums[0]||0,nums[1]||0,nums[2]||0]}function lum([r,g,b]:[number,number,number]){const c=(v:number)=>{const s=v/255;return s<=.03928?s/12.92:Math.pow((s+.055)/1.055,2.4)};return .2126*c(r)+.7152*c(g)+.0722*c(b)}function ratio(a:[number,number,number],b:[number,number,number]){const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)}

test("deployed workflow pages expose requested production surfaces",async({page})=>{await BASE_APIS(page);for(const[path,heading]of [["/",/Create campaign content/i],["/avatars",/Avatars/i],["/sites",/^Sites$/i],["/library",/^Library$/i],["/calendar",/Content Calendar/i],["/campaigns",/^Campaigns$/i],["/podcast-interview",/Podcast \/ split-screen composer/i]] as [string,RegExp][]){await page.goto(path,{waitUntil:"domcontentloaded"});await expect(page.getByRole("heading",{name:heading})).toBeVisible({timeout:15000})}});

test("deployed Create is AI-planned and keeps all engines plus canonical avatars",async({page})=>{await BASE_APIS(page);await page.goto("/");for(const provider of ["Google Veo 3.1","xAI Grok Imagine","A2E AI router","Hedra"])await expect(page.getByRole("button",{name:new RegExp(provider,"i")})).toBeVisible();await expect(page.getByText("AI campaign plan",{exact:true})).toBeVisible();await expect(page.getByLabel("Choose canonical avatar")).toBeVisible()});

test("deployed Avatars labels NVIDIA portrait-only and keeps edit-capable providers",async({page})=>{await BASE_APIS(page);await page.goto("/avatars");await page.getByRole("button",{name:/Image: gemini/i}).click();await expect(page.getByRole("button",{name:/NVIDIA FLUX.2 Klein 4B/i})).toBeEnabled();await expect(page.getByText(/Fresh portraits only on hosted endpoint/i)).toBeVisible();await expect(page.getByRole("button",{name:/Google Gemini image generation/i})).toBeEnabled();await expect(page.getByRole("button",{name:/OpenAI image generation/i})).toBeEnabled()});

test("deployed Sites starts URL-first AI research instead of questionnaire",async({page})=>{await BASE_APIS(page);await page.goto("/sites");await page.getByRole("button",{name:/Add site/i}).click();await expect(page.getByText("1. Let AI learn the website")).toBeVisible();await expect(page.getByRole("button",{name:"Research site with AI"})).toBeDisabled();await expect(page.getByLabel("CMS / publishing target")).toHaveCount(0)});

test("deployed split-screen offers upload or AI upper and relationship presets",async({page})=>{await BASE_APIS(page);await page.goto("/podcast-interview");await expect(page.getByRole("button",{name:"Upload video"})).toBeVisible();await expect(page.getByRole("button",{name:"AI generate"})).toBeVisible();await expect(page.getByLabel("Split relationship")).toContainText("Studio anchor asks · field reporter answers");await expect(page.getByLabel("Campaign subject")).toContainText("Car Accident")});

test("deployed Calendar exposes owner review workflow",async({page})=>{await BASE_APIS(page);await page.goto("/calendar");await expect(page.getByText(/Generated blog articles, images and videos land here automatically/i)).toBeVisible();await expect(page.getByRole("button",{name:/Add post/i})).toBeVisible();await expect(page.getByText(/Owner review queue/i)).toBeVisible()});

test("deployed shared text buttons meet WCAG AA contrast",async({page})=>{await BASE_APIS(page);for(const path of ["/","/sites","/library","/calendar","/avatars","/campaigns","/podcast-interview"]){await page.goto(path);const buttons=page.locator("button:not([disabled])");for(let i=0;i<await buttons.count();i++){const b=buttons.nth(i);if(!(await b.isVisible()))continue;const text=(await b.innerText()).trim();if(!text)continue;const s=await b.evaluate(el=>{const x=getComputedStyle(el);return{fg:x.color,bg:x.backgroundColor}});if(s.bg==="rgba(0, 0, 0, 0)"||s.bg==="transparent")continue;expect(ratio(rgb(s.fg),rgb(s.bg)),`${path}: ${text}`).toBeGreaterThanOrEqual(4.5)}}});
