import { expect, test } from "@playwright/test";
import { stubAuthenticatedSession } from "./helpers";

const ONE_PIXEL_PNG="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z9ZkAAAAASUVORK5CYII=";
const splitPlan={hook:"LIVE UPDATE",caption:"A quick field update on what to document after a collision.",relationshipSummary:"Studio anchor asks; field reporter answers.",upper:{mission:"Ask what matters immediately after a collision.",subject:"TV studio anchor at news desk.",script:"What should drivers document before leaving the scene?",visualDirection:"One continuous studio shot."},lower:{mission:"Answer with practical documentation guidance.",subject:"Professional field reporter beside a safe roadside location.",script:"If it is safe, photograph the vehicles, roadway, visible damage, and identifying information before details disappear.",visualDirection:"Stable field-report shot."}};

test("split-screen supports AI upper plus canonical Hedra lower and Calendar handoff",async({page})=>{
  await stubAuthenticatedSession(page);let generateCalls:any[]=[];let calendarPayload:any=null;
  await page.route("**/api/admin/avatars",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({avatars:[{id:"female-anchor-01",name:"Female Anchor 01",referenceImage:"x",wardrobeRegenerationPrompt:null,views:{front:{status:"ready"}}}]})}));
  await page.route("**/api/admin/avatars/female-anchor-01/asset?view=front",route=>route.fulfill({status:200,contentType:"image/png",body:Buffer.from(ONE_PIXEL_PNG,"base64")}));
  await page.route("**/api/internal/split-plan",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({plan:splitPlan})}));
  await page.route("**/api/internal/generate",async route=>{const body=await route.request().postDataJSON();generateCalls.push(body);const id=generateCalls.length===1?"top-job":"bottom-job";return route.fulfill({status:202,contentType:"application/json",body:JSON.stringify({job:{id,status:"running"}})})});
  await page.route("**/api/v1/video/top-job",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({id:"top-job",status:"succeeded",fileUrl:"/api/v1/video/top-job/file"})}));
  await page.route("**/api/v1/video/bottom-job",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({id:"bottom-job",status:"succeeded",fileUrl:"/api/v1/video/bottom-job/file"})}));
  await page.route("**/api/v1/video/*/file",route=>route.fulfill({status:200,contentType:"video/mp4",body:""}));
  await page.route("**/api/calendar",async route=>{if(route.request().method()!=="POST")return route.continue();calendarPayload=await route.request().postDataJSON();return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({post:{id:"post-1",...calendarPayload}})})});
  await page.goto("/podcast-interview");await expect(page.getByRole("heading",{name:"Podcast / split-screen composer"})).toBeVisible();await page.getByRole("button",{name:"AI generate"}).click();await page.getByLabel("Campaign subject").selectOption("car_accident");await page.getByLabel("Split relationship").selectOption("anchor_field");await page.getByLabel("Upper AI engine").selectOption("veo");await page.getByLabel("Canonical lower avatar").selectOption("female-anchor-01");await page.getByRole("button",{name:"Plan both lanes with AI"}).click();await expect(page.getByText("What should drivers document before leaving the scene?")).toBeVisible();await expect(page.getByText(/If it is safe, photograph/)).toBeVisible();
  await page.locator('input[type="file"][accept="audio/*"]').setInputFiles({name:"voice.mp3",mimeType:"audio/mpeg",buffer:Buffer.from("fake-audio")});await page.getByRole("button",{name:"Generate upper + lower videos"}).click();expect(generateCalls).toHaveLength(2);expect(generateCalls[0].provider).toBe("veo");expect(generateCalls[1].provider).toBe("hedra");expect(generateCalls[1].durationSeconds).toBe(30);expect(generateCalls[1].audioBase64).toBeTruthy();
  await expect.poll(async()=>page.locator('video[src*="bottom-job"]').count(),{timeout:10000}).toBe(1);await page.getByRole("button",{name:"Send split-screen to Calendar"}).click();expect(calendarPayload.contentType).toBe("podcast");expect(calendarPayload.videoJobId).toBe("bottom-job");expect(calendarPayload.caption).toContain("field update");
});

test("split-screen still supports uploaded upper video",async({page})=>{await stubAuthenticatedSession(page);await page.route("**/api/admin/avatars",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({avatars:[]})}));await page.goto("/podcast-interview");await page.locator('input[type="file"][accept="video/*"]').setInputFiles({name:"context.mp4",mimeType:"video/mp4",buffer:Buffer.from("fake-video")});await expect(page.locator("video").first()).toBeVisible();await page.locator('input[type="range"]').fill("40");await expect(page.getByText("Top 40% · Bottom 60%" )).toBeVisible();});
