import { expect, test } from "@playwright/test";
import { stubAuthenticatedSession } from "./helpers";

test("Sites supports blog-only onboarding header code CMS publishing and calendar planning",async({page})=>{
  await stubAuthenticatedSession(page);let sites:any[]=[];let planned:any=null;let lastSave:any=null;
  await page.route("**/api/sites",async route=>{const req=route.request();if(req.method()==="GET"&&new URL(req.url()).pathname==="/api/sites")return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({sites})});if(req.method()==="POST"&&new URL(req.url()).pathname==="/api/sites"){const input=await req.postDataJSON();lastSave=input;const site={id:"site-1",...input,url:"https://example.com",verifiedAt:null,lastSeenAt:null,status:"setup",bridgeToken:"ve_site_test",publishConfigured:Boolean(input.publishEndpoint&&input.publishSecret)};sites=[site];return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({site})});}return route.continue();});
  await page.route("**/api/sites/site-1",async route=>{if(route.request().method()==="PATCH"){const input=await route.request().postDataJSON();lastSave=input;sites=[{...sites[0],...input,publishConfigured:Boolean(input.publishEndpoint&&(input.publishSecret||sites[0].publishConfigured))}];return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({site:sites[0]})});}return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({site:{...sites[0],bridgeToken:"ve_site_test"}})});});
  await page.route("**/api/sites/site-1/plan",async route=>{planned=await route.request().postDataJSON();return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({ok:true,count:14})});});
  await page.goto("/sites");
  await expect(page.getByRole("heading",{name:"Sites",exact:true})).toBeVisible();
  await expect(page.getByText(/blog \+ images only/i)).toBeVisible();
  await page.getByRole("button",{name:"Add site",exact:true}).click();
  await page.getByRole("textbox",{name:"Site name",exact:true}).fill("Example Blog");
  await page.getByRole("textbox",{name:"Website URL",exact:true}).fill("https://example.com");
  await page.locator("label").filter({hasText:/^Image style/}).locator("select").selectOption("hyper-realistic");
  await page.locator("label").filter({hasText:/^Publishing mode/}).locator("select").selectOption("wordpress-rest");
  await page.getByRole("textbox",{name:"WordPress username",exact:true}).fill("publisher");
  await page.getByRole("textbox",{name:"Application password",exact:true}).fill("app-pass");
  await expect(page.getByText(/No video settings exist in this workflow/i)).toBeVisible();
  await page.getByRole("button",{name:"Save site",exact:true}).click();
  expect(lastSave.publishMode).toBe("wordpress-rest");
  expect(lastSave.publishEndpoint).toContain("/wp-json/wp/v2/posts");
  await expect(page.getByText("Install header code",{exact:true})).toBeVisible();
  await expect(page.locator("pre")).toContainText("/api/sites/bridge.js?key=ve_site_test");
  await page.getByRole("button",{name:"Close",exact:true}).last().click();
  await page.getByLabel("Planning horizon for Example Blog",{exact:true}).selectOption("14");
  await page.getByRole("button",{name:"Generate blog calendar",exact:true}).click();
  await expect(page.getByText(/14 NVIDIA blog drafts added to Calendar/)).toBeVisible();
  expect(planned.horizonDays).toBe(14);
});
