import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { ensureBrandContactInCaption } from "@/lib/brand-contact";
import "@/lib/calendar-assets";
const NETWORKS=new Set(["instagram","facebook","youtube","tiktok","linkedin","website"]),STATUSES=new Set(["draft","pending","approved","published","failed"]),FORMATS=new Set(["podcast","ugc","newsroom","direct","cinematic","image","blog"]);
function rowToPost(row:any){return{id:row.id,title:row.title,network:row.network,scheduledAt:row.scheduled_at,status:row.status,autoPost:Boolean(row.auto_post),caption:row.caption,contentType:row.content_type||"ugc",videoJobId:row.video_job_id,upperJobId:row.upper_job_id,lowerJobId:row.lower_job_id,mediaUrl:row.media_url,mediaType:row.media_type,sourceAssetKey:row.source_asset_key,siteId:row.site_id,campaignId:row.campaign_id,planningHorizonDays:row.planning_horizon_days,contentBody:row.content_body,seoTitle:row.seo_title,metaDescription:row.meta_description,slug:row.slug,focusKeyword:row.focus_keyword,generationStatus:row.generation_status||"ready",connectedAccountId:row.connected_account_id,publishedAt:row.published_at,error:row.error,createdAt:row.created_at,updatedAt:row.updated_at};}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){
  if(!(await requireAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});
  const{id}=await params,current=db.prepare("SELECT * FROM scheduled_posts WHERE id=?").get(id) as any;if(!current)return NextResponse.json({error:"Not found"},{status:404});
  const body=await req.json().catch(()=>({})),title=body.title===undefined?current.title:String(body.title).trim().slice(0,180),network=body.network===undefined?current.network:String(body.network).toLowerCase(),status=body.status===undefined?current.status:String(body.status),contentType=body.contentType===undefined?(current.content_type||"ugc"):String(body.contentType).toLowerCase();
  let scheduledAt=current.scheduled_at;if(body.scheduledAt!==undefined){const d=new Date(String(body.scheduledAt));if(Number.isNaN(d.getTime()))return NextResponse.json({error:"Invalid scheduledAt"},{status:400});scheduledAt=d.toISOString();}
  if(!title)return NextResponse.json({error:"Title is required"},{status:400});if(!NETWORKS.has(network)||!STATUSES.has(status)||!FORMATS.has(contentType))return NextResponse.json({error:"Invalid schedule fields"},{status:400});
  const videoJobId=body.videoJobId===undefined?current.video_job_id:(body.videoJobId?String(body.videoJobId):null);
  const mediaUrl=body.mediaUrl===undefined?current.media_url:(body.mediaUrl?String(body.mediaUrl):null);
  const mediaType=body.mediaType===undefined?current.media_type:(body.mediaType?String(body.mediaType):null);
  const generationStatus=body.generationStatus===undefined?current.generation_status:String(body.generationStatus);
  const error=body.error===undefined?current.error:(body.error?String(body.error).slice(0,2000):null);
  db.prepare(`UPDATE scheduled_posts SET title=?,network=?,scheduled_at=?,status=?,auto_post=?,caption=?,content_type=?,connected_account_id=?,media_url=?,media_type=?,site_id=?,campaign_id=?,planning_horizon_days=?,content_body=?,seo_title=?,meta_description=?,slug=?,focus_keyword=?,generation_status=?,video_job_id=?,error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(
    title,network,scheduledAt,status,body.autoPost===undefined?current.auto_post:body.autoPost?1:0,body.caption===undefined?current.caption:ensureBrandContactInCaption(String(body.caption)).slice(0,5000),contentType,
    body.connectedAccountId===undefined?current.connected_account_id:(body.connectedAccountId?String(body.connectedAccountId):null),mediaUrl,mediaType,body.siteId===undefined?current.site_id:(body.siteId?String(body.siteId):null),body.campaignId===undefined?current.campaign_id:(body.campaignId?String(body.campaignId):null),body.planningHorizonDays===undefined?current.planning_horizon_days:Number(body.planningHorizonDays)||null,
    body.contentBody===undefined?current.content_body:(body.contentBody?String(body.contentBody):null),body.seoTitle===undefined?current.seo_title:(body.seoTitle?String(body.seoTitle).slice(0,180):null),body.metaDescription===undefined?current.meta_description:(body.metaDescription?String(body.metaDescription).slice(0,300):null),body.slug===undefined?current.slug:(body.slug?String(body.slug).slice(0,180):null),body.focusKeyword===undefined?current.focus_keyword:(body.focusKeyword?String(body.focusKeyword).slice(0,180):null),generationStatus,videoJobId,error,id
  );
  if(current.source_asset_key?.startsWith("blog:")&&body.contentBody!==undefined){const blogId=String(current.source_asset_key).slice(5);db.prepare("UPDATE blog_posts SET body_markdown=?,meta_title=?,meta_description=?,slug=?,focus_keyword=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(body.contentBody||null,body.seoTitle===undefined?current.seo_title:body.seoTitle||null,body.metaDescription===undefined?current.meta_description:body.metaDescription||null,body.slug===undefined?current.slug:body.slug||null,body.focusKeyword===undefined?current.focusKeyword:body.focusKeyword||null,blogId);}
  return NextResponse.json({post:rowToPost(db.prepare("SELECT * FROM scheduled_posts WHERE id=?").get(id))});
}
export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){if(!(await requireAdmin()))return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params,result=db.prepare("DELETE FROM scheduled_posts WHERE id=?").run(id);if(!result.changes)return NextResponse.json({error:"Not found"},{status:404});return NextResponse.json({ok:true});}
