"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, Film, Image as ImageIcon, Plus, RefreshCcw, Shuffle } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type Campaign={id:string;name:string;category:string;website?:string|null;mission:string;avatarId?:string|null;planningHorizonDays?:number;contentType?:string;outputMode?:"video"|"image"|"auto_mix";videoProvider?:string|null;upperProvider?:string|null;splitPercent?:number|null;splitRelationship?:string|null;status:string;createdAt:string};

export function CampaignsConsole({onCreateNew}:{onCreateNew?:()=>void}){
  const[campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[query,setQuery]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/campaigns",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setCampaigns(d.campaigns||[])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?campaigns.filter(c=>[c.name,c.category,c.contentType,c.outputMode,c.mission].some(v=>String(v||"").toLowerCase().includes(q))):campaigns},[campaigns,query]);
  return <div>
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold tracking-tight">Campaigns</h2><p className="mt-1 max-w-3xl text-sm text-slate-600">Saved campaign plans live here. New campaign setup and generation happen once in Create; Calendar handles scheduling, approval and posting.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={load} disabled={loading}><RefreshCcw size={14} className={`mr-2 ${loading?"animate-spin":""}`}/>Refresh</Button>{onCreateNew?<Button onClick={onCreateNew}><Plus size={14} className="mr-2"/>Create campaign</Button>:<Link href="/"><Button><Plus size={14} className="mr-2"/>Create campaign</Button></Link>}</div></div>
    {error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <Card title="Saved campaigns" actions={<input aria-label="Search campaigns" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campaigns" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/>}>
      <div className="grid gap-3">{visible.map(c=><article key={c.id} className="rounded-2xl border bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-900">{c.name}</h3><OutputBadge mode={c.outputMode||"video"}/><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold uppercase text-slate-600">{c.status}</span></div><div className="mt-1 text-xs text-slate-500">{c.category.replaceAll("_"," ")} · {c.contentType||"cinematic"} · {c.planningHorizonDays||7} days{c.contentType==="podcast"?` · split ${c.splitPercent||35}% ${c.splitRelationship||"anchor_field"} · ${c.upperProvider||"grok"} / ${c.videoProvider||"lower"}`:""}</div>{c.website&&<div className="mt-1 truncate text-xs text-slate-500">{c.website}</div>}<p className="mt-3 line-clamp-3 max-w-3xl text-sm text-slate-700">{c.mission}</p></div><div className="flex shrink-0 gap-2">{onCreateNew?<Button size="sm" variant="secondary" onClick={onCreateNew}>Create from this flow</Button>:<Link href="/"><Button size="sm" variant="secondary">Create from this flow</Button></Link>}<Link href="/calendar"><Button size="sm"><CalendarDays size={13} className="mr-1"/>Calendar</Button></Link></div></div></article>)}{!loading&&!visible.length&&<div className="rounded-2xl border border-dashed p-10 text-center"><div className="text-sm font-medium text-slate-700">No saved campaigns yet.</div><p className="mt-1 text-xs text-slate-500">Create one campaign in the Create tab and fill its Calendar there.</p>{onCreateNew?<Button className="mt-4" onClick={onCreateNew}>Create first campaign</Button>:<Link href="/" className="mt-4 inline-block"><Button>Create first campaign</Button></Link>}</div>}</div>
    </Card>
  </div>;
}
function OutputBadge({mode}:{mode:string}){const Icon=mode==="image"?ImageIcon:mode==="auto_mix"?Shuffle:Film;const label=mode==="image"?"Still":mode==="auto_mix"?"Auto mix":"Video";return <span className="inline-flex items-center gap-1 rounded-full bg-violet-50 px-2 py-1 text-[10px] font-semibold uppercase text-violet-700"><Icon size={11}/>{label}</span>}
