"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Atom, Bird, BrainCircuit, CalendarPlus, Car, ChevronDown, ChevronUp, Cloud, Footprints, Instagram, Mic2, Play, RefreshCcw, Smartphone, Sparkles, Truck, Upload, UserRound, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const modes=[
  {id:"car_accident",title:"Car Accident",icon:Car,sub:"Roadside, collision, aftermath"},
  {id:"rideshare",title:"Rideshare / Uber / Lyft",icon:Smartphone,sub:"Passenger and driver scenarios"},
  {id:"trucking",title:"Trucking / 18-Wheeler",icon:Truck,sub:"Commercial vehicle incidents"},
  {id:"slip_fall",title:"Slip & Fall",icon:Footprints,sub:"Premises-liability scenarios"},
  {id:"ugc",title:"UGC Video",icon:WandSparkles,sub:"Creator-style campaign video"}
] as const;
const providers=[
  {id:"veo",label:"Google Veo 3.1",icon:Sparkles,cap:"8s cinematic",duration:8},
  {id:"grok",label:"xAI Grok Imagine",icon:Atom,cap:"up to 15s",duration:15},
  {id:"a2e",label:"A2E AI router",icon:Cloud,cap:"model dependent",duration:8},
  {id:"hedra",label:"Hedra",icon:Bird,cap:"15/30s avatar · audio driven",duration:30}
] as const;
type ProviderId=typeof providers[number]["id"];
type CategoryId=typeof modes[number]["id"];
type Job={id:string;provider?:ProviderId;status:string;error?:string;fileUrl?:string|null};
type MediaInput={base64:string;mime:string;name:string};
type AvatarOption={id:string;name:string;referenceImage:string|null;views?:{front?:{status?:string}}};
type CampaignPlan={mission:string;subject:string;script:string;hook:string;caption:string;visualDirection:string;rationale:string};

async function fileToMedia(file:File):Promise<MediaInput>{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});return{base64,mime:file.type||"application/octet-stream",name:file.name}}

export function GeneratorConsole(){
  const[category,setCategory]=useState<CategoryId>("car_accident"),[provider,setProvider]=useState<ProviderId>("veo"),[settings,setSettings]=useState<any>(null),[avatars,setAvatars]=useState<AvatarOption[]>([]),[selectedAvatar,setSelectedAvatar]=useState(""),[loadingAvatar,setLoadingAvatar]=useState(false);
  const[mission,setMission]=useState(""),[subject,setSubject]=useState(""),[script,setScript]=useState(""),[plan,setPlan]=useState<CampaignPlan|null>(null),[planning,setPlanning]=useState(false),[showOverrides,setShowOverrides]=useState(false);
  const[image,setImage]=useState<MediaInput|null>(null),[audio,setAudio]=useState<MediaInput|null>(null),[hedraDuration,setHedraDuration]=useState<15|30>(30),[job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(false),[scheduleState,setScheduleState]=useState<"idle"|"saving"|"saved">("idle"),[instagramState,setInstagramState]=useState<"idle"|"posting"|"posted">("idle"),[error,setError]=useState<string|null>(null);

  useEffect(()=>{Promise.all([fetch("/api/admin/settings").then(r=>r.ok?r.json():null),fetch("/api/admin/avatars",{cache:"no-store"}).then(r=>r.ok?r.json():{avatars:[]})]).then(([s,a])=>{const initial=(s?.defaultProvider||"veo") as ProviderId;if(s){setSettings(s);setProvider(initial)}setAvatars(a?.avatars||[]);void planCreative("car_accident",initial,"")}).catch(()=>{})},[]);
  useEffect(()=>{if(!job?.id||["succeeded","failed"].includes(job.status))return;const timer=setInterval(async()=>{const r=await fetch(`/api/v1/video/${job.id}`,{cache:"no-store"});if(r.ok){const d=await r.json();setJob(j=>({...j,...d} as Job))}},5000);return()=>clearInterval(timer)},[job?.id,job?.status]);

  const selected=providers.find(p=>p.id===provider)!;const selectedMode=modes.find(m=>m.id===category)!;const hedraReady=provider!=="hedra"||Boolean(image&&audio);const durationSeconds=provider==="hedra"?hedraDuration:selected.duration;
  function durationFor(p:ProviderId){return p==="hedra"?hedraDuration:providers.find(x=>x.id===p)!.duration}
  async function planCreative(nextCategory:CategoryId=category,nextProvider:ProviderId=provider,nextAvatarId:string=selectedAvatar){setPlanning(true);setError(null);try{const avatarName=avatars.find(a=>a.id===nextAvatarId)?.name||null;const r=await fetch("/api/internal/campaign-plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({category:nextCategory,provider:nextProvider,durationSeconds:durationFor(nextProvider),avatarName})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setPlan(d.plan);setMission(d.plan.mission);setSubject(d.plan.subject);setScript(d.plan.script||"")}catch(e){setPlan(null);setError(e instanceof Error?e.message:String(e))}finally{setPlanning(false)}}
  async function chooseImage(file?:File){if(!file)return;if(file.size>10*1024*1024){setError("Reference image must be 10MB or smaller.");return}setImage(await fileToMedia(file));setSelectedAvatar("");setError(null)}
  async function chooseAvatar(avatarId:string){setSelectedAvatar(avatarId);if(!avatarId){setImage(null);void planCreative(category,provider,"");return}const avatar=avatars.find(a=>a.id===avatarId);if(!avatar)return;setLoadingAvatar(true);setError(null);try{const view=avatar.views?.front?.status==="ready"?"front":"reference";if(view==="reference"&&!avatar.referenceImage)throw new Error("This avatar has no usable canonical/reference identity yet.");const r=await fetch(`/api/admin/avatars/${encodeURIComponent(avatar.id)}/asset?view=${view}`,{cache:"no-store"});if(!r.ok)throw new Error(`Could not load ${avatar.name} ${view} image`);const blob=await r.blob();setImage(await fileToMedia(new File([blob],`${avatar.id}-${view}.png`,{type:blob.type||"image/png"})));await planCreative(category,provider,avatarId)}catch(e){setSelectedAvatar("");setImage(null);setError(e instanceof Error?e.message:String(e))}finally{setLoadingAvatar(false)}}
  async function chooseAudio(file?:File){if(!file)return;if(file.size>105*1024*1024){setError("Driving audio must be 105MB or smaller.");return}setAudio(await fileToMedia(file));setError(null)}
  async function generate(){if(!plan&&!mission.trim()){setError("The AI creative plan is not ready. Click Regenerate AI plan first.");return}if(provider==="hedra"&&(!image||!audio)){setError("Hedra Character/Avatar needs both a canonical avatar/reference image and driving audio. Add both before generating.");return}setBusy(true);setJob(null);setError(null);setScheduleState("idle");setInstagramState("idle");try{const compiledMission=[mission,plan?.visualDirection?`Visual direction: ${plan.visualDirection}`:""].filter(Boolean).join("\n");const r=await fetch("/api/internal/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider,category,mission:compiledMission,subject,script,durationSeconds,imageBase64:image?.base64,imageMimeType:image?.mime,audioBase64:audio?.base64,audioMimeType:audio?.mime})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setJob({...d.job,provider})}catch(e){const message=e instanceof Error?e.message:String(e);setJob({id:"",provider,status:"failed",error:message});setError(message)}finally{setBusy(false)}}
  async function sendToCalendar(){if(!job?.id||job.status!=="succeeded")return;setScheduleState("saving");setError(null);try{const when=new Date(Date.now()+86400000);const r=await fetch("/api/calendar",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:`${selectedMode.title} · ${selected.label}`,network:"instagram",scheduledAt:when.toISOString(),status:"pending",autoPost:false,contentType:category==="ugc"?"ugc":"cinematic",caption:plan?.caption||mission||script||`${selectedMode.title} generated video`,videoJobId:job.id})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setScheduleState("saved")}catch(e){setScheduleState("idle");setError(e instanceof Error?e.message:String(e))}}
  async function postToInstagram(){if(!job?.id||job.status!=="succeeded")return;if(!confirm("Publish this generated video to the connected Instagram Business/Creator account now?"))return;setInstagramState("posting");setError(null);try{const r=await fetch("/api/publish/instagram",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId:job.id,caption:plan?.caption||mission||script||`${selectedMode.title} generated video`})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setInstagramState("posted")}catch(e){setInstagramState("idle");setError(e instanceof Error?e.message:String(e))}}

  return <main>
    <div className="mb-7"><div className="mb-2 text-sm font-medium text-violet-700">Campaign production</div><h1 className="text-[34px] font-semibold leading-tight tracking-tight text-slate-900">Create campaign content</h1><p className="mt-1 max-w-3xl text-[15px] text-slate-600">Choose the campaign type, engine, and spokesperson. NVIDIA plans the hook, scene, direction, dialogue and post copy automatically; you can override the plan before generation.</p></div>
    <div className="mb-6 grid gap-3 sm:grid-cols-2"><Link href="/podcast-interview" className="rounded-2xl border border-violet-300 bg-violet-50 p-4 transition hover:border-violet-500"><Mic2 className="text-violet-600"/><div className="mt-2 font-semibold">Podcast / split-screen</div><div className="text-xs text-slate-600">Uploaded source video on top + 15/30s AI host below. Hedra preferred, other engines remain available.</div></Link><button onClick={()=>{setCategory("ugc");void planCreative("ugc",provider,selectedAvatar)}} className="rounded-2xl border border-slate-200 bg-white p-4 text-left hover:border-violet-300"><WandSparkles className="text-slate-600"/><div className="mt-2 font-semibold">UGC / campaign shot</div><div className="text-xs text-slate-600">AI-planned direct-to-camera, newsroom, accident scenario, or cinematic creative.</div></button></div>
    <div className="mb-2 text-xs uppercase tracking-wider text-slate-500">Video engine</div><div className="grid gap-3 md:grid-cols-4">{providers.map(p=>{const I=p.icon,active=provider===p.id,configured=settings?.providers?.[p.id]?.keyConfigured;return <button key={p.id} onClick={()=>{setProvider(p.id);setError(null);void planCreative(category,p.id,selectedAvatar)}} className={`rounded-2xl border p-4 text-left transition ${active?"border-violet-400 bg-violet-50 ring-1 ring-violet-200":"border-slate-200 bg-white hover:border-violet-300"}`}><I className={active?"text-violet-600":"text-slate-500"}/><div className="mt-2 font-medium">{p.label}</div><div className="text-xs text-slate-500">{p.cap}{configured===false?" · key needed":""}</div></button>})}</div>
    <div className="mb-2 mt-6 text-xs uppercase tracking-wider text-slate-500">Campaign type · AI creative brief</div><div className="grid gap-3 md:grid-cols-5">{modes.map(m=>{const I=m.icon,active=category===m.id;return <button key={m.id} onClick={()=>{setCategory(m.id);void planCreative(m.id,provider,selectedAvatar)}} className={`rounded-2xl border p-4 text-left transition ${active?"border-violet-400 bg-violet-50":"border-slate-200 bg-white hover:border-violet-300"}`}><I/><div className="mt-2 font-medium">{m.title}</div><div className="text-xs text-slate-500">{m.sub}</div></button>})}</div>
    {error&&<div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="soro-card p-5"><div className="grid gap-4">
      <div className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-semibold text-violet-950"><BrainCircuit size={17}/>AI campaign plan</div><p className="mt-1 text-xs text-violet-800">The selected campaign card is the brief. NVIDIA writes the execution plan; no blank prompt is required.</p></div><Button size="sm" variant="secondary" onClick={()=>planCreative()} disabled={planning}>{planning?<><RefreshCcw size={13} className="mr-1 animate-spin"/>Planning…</>:"Regenerate AI plan"}</Button></div>{plan&&!planning&&<div className="mt-4 grid gap-3 text-sm"><div><div className="text-[10px] font-semibold uppercase text-violet-700">Hook</div><div className="font-semibold text-slate-900">{plan.hook}</div></div><div><div className="text-[10px] font-semibold uppercase text-violet-700">Creative mission</div><div className="text-slate-700">{mission}</div></div><div><div className="text-[10px] font-semibold uppercase text-violet-700">Visual direction</div><div className="text-slate-700">{plan.visualDirection}</div></div>{script&&<div><div className="text-[10px] font-semibold uppercase text-violet-700">Dialogue</div><div className="text-slate-700">{script}</div></div>}<div className="text-xs italic text-violet-800">{plan.rationale}</div></div>}{planning&&<div className="mt-4 text-sm text-violet-800">Planning the selected campaign and provider…</div>}</div>
      <button type="button" onClick={()=>setShowOverrides(v=>!v)} className="flex w-full items-center justify-between rounded-xl border bg-slate-50 px-4 py-3 text-left text-sm font-semibold text-slate-800"><span>Optional operator overrides</span>{showOverrides?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>{showOverrides&&<div className="grid gap-4"><label className="grid gap-2 text-sm"><span className="font-medium text-slate-700">Mission override</span><Textarea value={mission} onChange={e=>setMission(e.target.value)}/></label><label className="grid gap-2 text-sm"><span className="font-medium text-slate-700">Subject / spokesperson override</span><Input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="grid gap-2 text-sm"><span className="font-medium text-slate-700">Dialogue override</span><Textarea value={script} onChange={e=>setScript(e.target.value)}/></label></div>}
      <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-800"><UserRound size={16}/>Spokesperson / reference</div><label className="grid gap-2 text-sm"><span className="font-medium text-slate-700">Choose canonical avatar</span><select aria-label="Choose canonical avatar" value={selectedAvatar} onChange={e=>chooseAvatar(e.target.value)} disabled={loadingAvatar} className="h-11 rounded-xl border border-slate-200 bg-white px-3"><option value="">No avatar · use uploaded reference</option>{avatars.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{selectedAvatar&&<div className="mt-2 text-xs text-emerald-700">Loaded canonical image for {avatars.find(a=>a.id===selectedAvatar)?.name}.</div>}<div className="my-3 flex items-center gap-2 text-[10px] uppercase tracking-wider text-slate-400"><span className="h-px flex-1 bg-slate-200"/>or upload one-off reference<span className="h-px flex-1 bg-slate-200"/></div><label className="grid gap-2 text-sm"><span className="font-medium text-slate-700">Reference image {provider==="hedra"?"(required if no avatar selected)":"(optional)"}</span><div className="flex items-center gap-3"><Input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/><Upload size={18}/></div>{image&&<span className="text-xs text-emerald-700">Using: {image.name}</span>}</label></div>
      {provider==="hedra"&&<div className="grid gap-4 rounded-xl border border-violet-200 bg-violet-50 p-4"><label className="grid gap-1 text-sm"><span className="font-medium text-violet-900">Hedra duration</span><select value={hedraDuration} onChange={e=>{const value=Number(e.target.value) as 15|30;setHedraDuration(value);void planCreative(category,"hedra",selectedAvatar)}} className="h-11 rounded-xl border border-violet-200 bg-white px-3"><option value={15}>15 seconds</option><option value={30}>30 seconds</option></select></label><label className="grid gap-2 text-sm"><span className="font-medium text-violet-900">Driving audio (required)</span><Input type="file" accept="audio/*" onChange={e=>chooseAudio(e.target.files?.[0])}/>{audio&&<span className="text-xs text-emerald-700">Loaded: {audio.name}</span>}<span className="text-xs text-violet-700">Character/Avatar models animate the selected canonical identity from this audio.</span></label></div>}
      <Button size="lg" disabled={busy||planning||loadingAvatar||!hedraReady||!plan} onClick={generate}><Play size={17} className="mr-2"/>{busy?`Starting ${selected.label}…`:`Generate ${durationSeconds}s with ${selected.label}`}</Button>
    </div></div>
    <div className="soro-card min-h-[470px] p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><div className="font-medium">Output</div><div className="text-xs text-slate-500">{durationSeconds}s · {selected.label} · provider-specific generation</div></div>{job&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold uppercase">{job.status}</span>}</div>{!job&&<div className="grid h-[330px] place-items-center rounded-xl border border-dashed border-slate-200 text-center text-sm text-slate-500">AI-planned generated video appears here.</div>}{job?.status==="failed"&&<div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{job.error}</div>}{job&&!["succeeded","failed"].includes(job.status)&&<div className="grid h-[330px] place-items-center text-sm"><div className="text-center"><div className="mx-auto mb-3 h-9 w-9 animate-spin rounded-full border-2 border-slate-200 border-t-violet-600"/>{selected.label} is generating…</div></div>}{job?.status==="succeeded"&&job.fileUrl&&<div><video src={job.fileUrl} className="max-h-[430px] w-full rounded-xl bg-black" controls autoPlay playsInline/><div className="mt-4 flex flex-wrap items-center gap-2"><Button onClick={sendToCalendar} disabled={scheduleState!=="idle"}><CalendarPlus size={15} className="mr-2"/>{scheduleState==="saved"?"Added to Calendar":scheduleState==="saving"?"Adding…":"Send to approval Calendar"}</Button><Button variant="secondary" onClick={postToInstagram} disabled={instagramState!=="idle"}><Instagram size={15} className="mr-2"/>{instagramState==="posted"?"Posted to Instagram":instagramState==="posting"?"Publishing…":"Post to Instagram now"}</Button>{scheduleState==="saved"&&<Link href="/calendar" className="text-sm font-medium text-violet-700 hover:underline">Review scheduled post →</Link>}</div></div>}</div>
    </div>
  </main>;
}
