// Locked brand footer (operator directive 2026-08-27).
//
// EVERY NVIDIA-generated caption (Creator tab, public-copy captioner, monitor
// summaries) MUST end with this exact three-line block, in this exact order,
// with no characters added or removed. It is the firm's public marketing
// closer, with the disclaimer and hashtags that satisfy Florida Bar
// advertising rules + the operator's own voice standard.
//
// Hard-locked 2026-08-27 by direct operator instruction:
//   "every prompt generated by nvidia must end with this"
//     Visit CaseClosedFL.com or call (561) 566-1360 for a free consultation, no pressure.
//     General information only—not legal advice.
//     #Florida #SlipAndFall #CaseClosedFL
//
// (The third-line hashtag block re-emits the operator's sample — the model
// is allowed to swap #SlipAndFall for a category-relevant tag, but the
// 3-line shape stays the same.)

export const BRAND_FOOTER = `Visit CaseClosedFL.com or call (561) 566-1360 for a free consultation, no pressure.\nGeneral information only—not legal advice.\n#Florida #SlipAndFall #CaseClosedFL`;

/**
 * Force a caption to end with the brand footer. If the model already emitted
 * the footer, we leave it alone. Otherwise we append it on its own line.
 * De-duplicates whitespace and trims to the Instagram caption limit.
 */
export function applyBrandFooter(caption: string): string {
  const trimmed = String(caption || "").trim();
  if (!trimmed) return BRAND_FOOTER;
  // Already contains the closing hashtag block? leave the operator's voice alone.
  if (/#CaseClosedFL\b/.test(trimmed) && /VisitCaseClosedFL\.com/.test(trimmed.replace(/\s+/g, ""))) {
    return trimmed;
  }
  const joined = `${trimmed.replace(/\s+$/g, "")}\n\n${BRAND_FOOTER}`.replace(/\n{3,}/g, "\n\n");
  return joined.slice(0, 4900);
}
