import crypto from "node:crypto";
import { db } from "@/lib/db";
import { compileVeoPrompt } from "@/lib/prompt-compiler";
import type { CampaignCategory } from "@/lib/prompts";
import { getEngineSettings } from "@/lib/settings";
import { PROVIDERS, getDefaultProvider, type ProviderId } from "@/lib/providers";
import { ensureAssetCalendarPost } from "@/lib/calendar-assets";
import * as veo from "@/lib/veo";import * as grok from "@/lib/grok";import * as a2e from "@/lib/a2e";import * as hedra from "@/lib/hedra";
export type CreateJobInput={source:"admin"|"api";provider?:ProviderId;category:CampaignCategory;mission?:string;subject?:string;script?:string;aspectRatio?:"9:16"|"16:9";resolution?:"720p"|"1080p"|"4k";model?:string;durationSeconds?:number;imageBase64?:string;imageMimeType?:string;audioBase64?:string;audioMimeType?:string};
function modelForProvider(p:ProviderId,requested:string|undefined){const def=PROVIDERS[p];if(requested&&def.modelChoices.includes(requested))return requested;const raw=(db.prepare("SELECT value FROM settings WHERE key = ?").get(`${p}_model`) as {value:string}|undefined)?.value;return raw||def.defaultModel;}
export async function createJob(input:CreateJobInput){const defaults=getEngineSettings(),provider:ProviderId=input.provider||defaults.defaultProvider||getDefaultProvider(),id=crypto.randomUUID(),prompt=compileVeoPrompt(input),model=modelForProvider(provider,input.model),aspect=input.aspectRatio||defaults.aspectRatio,resolution=input.resolution||defaults.resolution;db.prepare("INSERT INTO video_jobs(id,source,category,prompt,provider,model,aspect_ratio,resolution,status) VALUES(?,?,?,?,?,?,?,?,?)").run(id,input.source,input.category,prompt,provider,model,aspect,resolution,"starting");try{let operation:string;if(provider==="veo")operation=await veo.startOneShot({prompt,model,aspectRatio:aspect,resolution,imageBase64:input.imageBase64,imageMimeType:input.imageMimeType});else if(provider==="grok")operation=await grok.startOneShot({prompt,model,aspectRatio:aspect,resolution,imageBase64:input.imageBase64,imageMimeType:input.imageMimeType});else if(provider==="hedra")operation=await hedra.startOneShot({prompt,model,aspectRatio:aspect,resolution,durationSeconds:input.durationSeconds,imageBase64:input.imageBase64,imageMimeType:input.imageMimeType,audioBase64:input.audioBase64,audioMimeType:input.audioMimeType});else operation=await a2e.startOneShot({prompt,model,aspectRatio:aspect,resolution,imageBase64:input.imageBase64,imageMimeType:input.imageMimeType});db.prepare("UPDATE video_jobs SET provider_operation=?,status='running',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(operation,id);return getJob(id)!;}catch(error){const message=error instanceof Error?error.message:String(error);db.prepare("UPDATE video_jobs SET status='failed',error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(message,id);throw error;}}
export function getJob(id:string){return db.prepare("SELECT id,source,category,prompt,provider,model,aspect_ratio as aspectRatio,resolution,provider_operation as providerOperation,status,error,output_path as outputPath,created_at as createdAt,updated_at as updatedAt FROM video_jobs WHERE id=?").get(id) as any;}
export async function refreshJob(id:string,options?:{ensureCalendar?:boolean}){const job=getJob(id);if(!job)return null;if(["succeeded","failed"].includes(job.status))return job;if(!job.providerOperation)return job;try{let result:{done:false}|{done:true;outputPath:string};if(job.provider==="grok")result=await grok.pollOneShot(job.providerOperation,id);else if(job.provider==="a2e")result=await a2e.pollOneShot(job.providerOperation,id,job.resolution);else if(job.provider==="hedra")result=await hedra.pollOneShot(job.providerOperation,id,job.resolution);else result=await veo.pollOneShot(job.providerOperation,id);if(!result.done)return job;db.prepare("UPDATE video_jobs SET status='succeeded',output_path=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(result.outputPath,id);if(options?.ensureCalendar!==false)ensureAssetCalendarPost({sourceKey:`video:${id}`,title:`${String(job.category).replaceAll("_"," ")} · ${job.provider}`,contentType:job.category==="ugc"?"ugc":"cinematic",mediaUrl:`/api/v1/video/${id}/file`,mediaType:"video/mp4",caption:job.prompt?.slice(0,1000)||"Generated campaign video",videoJobId:id});}catch(error){const message=error instanceof Error?error.message:String(error);db.prepare("UPDATE video_jobs SET status='failed',error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(message,id);}return getJob(id);}
