"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AudioLines, BrainCircuit, CalendarPlus, ImagePlus, Mic2, Play, RefreshCcw, Sparkles, Upload, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AuthGuard } from "@/components/auth-guard";
import { Button } from "@/components/ui/button";

type ProviderId="hedra"|"grok"|"veo"|"a2e";
type UpperProvider="veo"|"grok"|"a2e";
type Job={id:string;status:string;error?:string;fileUrl?:string|null;provider?:ProviderId};
type Avatar={id:string;name:string;referenceImage:string|null;wardrobeRegenerationPrompt?:string|null;views?:{front?:{status?:string}}};
type SplitPlan={hook:string;caption:string;relationshipSummary:string;upper:{mission:string;subject:string;script:string;visualDirection:string};lower:{mission:string;subject:string;script:string;visualDirection:string}};

const SUBJECTS=[{id:"car_accident",label:"Car Accident"},{id:"rideshare",label:"Rideshare / Uber / Lyft"},{id:"trucking",label:"Trucking / 18-Wheeler"},{id:"slip_fall",label:"Slip & Fall"},{id:"ugc",label:"UGC / creator"}] as const;
const RELATIONSHIPS=[
  {id:"anchor_field",label:"Studio anchor asks · field reporter answers"},
  {id:"question_answer",label:"Upper asks · lower answers"},
  {id:"context_commentary",label:"Upper context · lower explains"},
  {id:"reaction",label:"Upper scenario · lower reacts"},
  {id:"parallel",label:"Parallel complementary stories"}
] as const;

function fileToBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error("Could not read file"));r.onload=()=>resolve(String(r.result||"").split(",")[1]||"");r.readAsDataURL(file)})}

export default function PodcastInterviewPage(){
  const[topMode,setTopMode]=useState<"upload"|"ai">("upload"),[topUrl,setTopUrl]=useState<string|null>(null),[topJob,setTopJob]=useState<Job|null>(null),[split,setSplit]=useState(33),[category,setCategory]=useState("car_accident"),[relationship,setRelationship]=useState("anchor_field"),[upperProvider,setUpperProvider]=useState<UpperProvider>("veo"),[lowerProvider,setLowerProvider]=useState<ProviderId>("hedra"),[durationSeconds,setDurationSeconds]=useState(30),[plan,setPlan]=useState<SplitPlan|null>(null),[planning,setPlanning]=useState(false);
  const[avatars,setAvatars]=useState<Avatar[]>([]),[selectedAvatar,setSelectedAvatar]=useState(""),[avatarBase64,setAvatarBase64]=useState<string|null>(null),[freshAvatarPrompt,setFreshAvatarPrompt]=useState("Photorealistic adult field reporter, professional attire, realistic broadcast location, natural skin texture, eye-level camera"),[freshAvatarModel,setFreshAvatarModel]=useState("black-forest-labs/flux.1-schnell"),[generatingAvatar,setGeneratingAvatar]=useState(false);
  const[audioName,setAudioName]=useState(""),[audioBase64,setAudioBase64]=useState<string|null>(null),[audioMimeType,setAudioMimeType]=useState<string|null>(null),[lowerJob,setLowerJob]=useState<Job|null>(null),[generating,setGenerating]=useState(false),[scheduleState,setScheduleState]=useState<"idle"|"saving"|"saved">("idle"),[error,setError]=useState<string|null>(null);

  useEffect(()=>{fetch("/api/admin/avatars",{cache:"no-store"}).then(r=>r.ok?r.json():{avatars:[]}).then(d=>setAvatars(d.avatars||[])).catch(()=>{})},[]);
  useEffect(()=>()=>{if(topUrl)URL.revokeObjectURL(topUrl)},[topUrl]);
  useEffect(()=>{for(const pair of [[topJob,setTopJob],[lowerJob,setLowerJob]] as const){const[job,setter]=pair;if(!job?.id||["succeeded","failed"].includes(job.status))continue;const t=setInterval(async()=>{const r=await fetch(`/api/v1/video/${job.id}`,{cache:"no-store"});if(r.ok){const d=await r.json();setter(j=>({...j,...d} as Job))}},4000);return()=>clearInterval(t)}},[topJob?.id,topJob?.status,lowerJob?.id,lowerJob?.status]);

  const lowerSeconds=lowerProvider==="hedra"?durationSeconds:lowerProvider==="grok"?15:8;const upperSeconds=upperProvider==="grok"?15:8;const bottomHeight=100-split;const selectedAvatarObj=useMemo(()=>avatars.find(a=>a.id===selectedAvatar),[avatars,selectedAvatar]);
  const topPreview=topMode==="upload"?topUrl:topJob?.status==="succeeded"?topJob.fileUrl:null;const lowerPreview=lowerJob?.status==="succeeded"?lowerJob.fileUrl:null;
  const canGenerateLower=Boolean(plan&&avatarBase64&&(lowerProvider!=="hedra"||audioBase64));const canGenerateBoth=Boolean(plan&&(topMode==="upload"?topUrl:true)&&canGenerateLower&&!generating);

  function chooseTop(file?:File){if(!file)return;if(!file.type.startsWith("video/")){setError("Choose a video file.");return}if(file.size>200*1024*1024){setError("Top video must be 200MB or smaller.");return}if(topUrl)URL.revokeObjectURL(topUrl);setTopUrl(URL.createObjectURL(file));setTopMode("upload");setTopJob(null);setError(null)}
  async function chooseAudio(file?:File){if(!file)return;if(!file.type.startsWith("audio/")){setError("Choose an audio file for Hedra.");return}if(file.size>105*1024*1024){setError("Hedra driving audio must be 105MB or smaller.");return}setAudioBase64(await fileToBase64(file));setAudioMimeType(file.type||"audio/mpeg");setAudioName(file.name);setError(null)}
  async function chooseAvatar(id:string){setSelectedAvatar(id);setAvatarBase64(null);if(!id)return;const avatar=avatars.find(a=>a.id===id);if(!avatar)return;try{let view="front";if(avatar.views?.front?.status!=="ready"){if(avatar.wardrobeRegenerationPrompt)throw new Error(`${avatar.name} has identity-only reference imagery and no campaign-safe canonical front view. Generate/upload a professional canonical front in Avatars before using this identity in Hedra.`);if(!avatar.referenceImage)throw new Error(`${avatar.name} has no usable image.`);view="reference"}const r=await fetch(`/api/admin/avatars/${encodeURIComponent(id)}/asset?view=${view}`,{cache:"no-store"});if(!r.ok)throw new Error(`Could not load ${avatar.name} ${view} image`);const blob=await r.blob();const base64=await fileToBase64(new File([blob],`${id}-${view}.png`,{type:blob.type||"image/png"}));setAvatarBase64(base64);setError(null);void planBoth(id)}catch(e){setSelectedAvatar("");setError(e instanceof Error?e.message:String(e))}}
  async function generateFreshAvatar(){setGeneratingAvatar(true);setError(null);try{const r=await fetch("/api/internal/nvidia/image",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:freshAvatarPrompt,model:freshAvatarModel})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setAvatarBase64(d.base64);setSelectedAvatar("")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setGeneratingAvatar(false)}}
  async function planBoth(nextAvatar=selectedAvatar){setPlanning(true);setError(null);try{const avatarName=avatars.find(a=>a.id===nextAvatar)?.name||null;const r=await fetch("/api/internal/split-plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({category,relationship,upperProvider,lowerProvider,upperSeconds,lowerSeconds,lowerAvatarName:avatarName})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setPlan(d.plan)}catch(e){setPlan(null);setError(e instanceof Error?e.message:String(e))}finally{setPlanning(false)}}
  async function startGeneration(payload:any){const r=await fetch("/api/internal/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d.job as Job}
  async function generateBoth(){if(!canGenerateBoth)return;setGenerating(true);setError(null);setTopJob(topMode==="ai"?null:topJob);setLowerJob(null);setScheduleState("idle");try{if(topMode==="ai"){const top=await startGeneration({provider:upperProvider,category,mission:`${plan!.upper.mission}\nVisual direction: ${plan!.upper.visualDirection}`,subject:plan!.upper.subject,script:plan!.upper.script,durationSeconds:upperSeconds,aspectRatio:"9:16",resolution:"1080p"});setTopJob({...top,provider:upperProvider})}const lower=await startGeneration({provider:lowerProvider,category,mission:`${plan!.lower.mission}\nVisual direction: ${plan!.lower.visualDirection}`,subject:plan!.lower.subject,script:plan!.lower.script,durationSeconds:lowerSeconds,aspectRatio:"9:16",resolution:"1080p",imageBase64:avatarBase64,imageMimeType:"image/png",audioBase64:lowerProvider==="hedra"?audioBase64:undefined,audioMimeType:lowerProvider==="hedra"?audioMimeType:undefined});setLowerJob({...lower,provider:lowerProvider})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setGenerating(false)}}
  async function sendToCalendar(){if(!lowerJob?.id||lowerJob.status!=="succeeded")return;setScheduleState("saving");try{const r=await fetch("/api/calendar",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:`Split-screen · ${SUBJECTS.find(s=>s.id===category)?.label||category}`,network:"instagram",scheduledAt:new Date(Date.now()+86400000).toISOString(),status:"pending",autoPost:false,contentType:"podcast",caption:plan?.caption||plan?.lower.mission||"Split-screen campaign",videoJobId:lowerJob.id})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setScheduleState("saved")}catch(e){setScheduleState("idle");setError(e instanceof Error?e.message:String(e))}}

  return <AuthGuard><AppShell><main>
    <div className="mb-6"><div className="mb-2 flex items-center gap-2 text-sm font-medium text-violet-700"><Mic2 size={16}/> Create · Split-screen</div><h1 className="text-[34px] font-semibold leading-tight tracking-tight text-slate-900">Podcast / split-screen composer</h1><p className="mt-1 max-w-4xl text-sm text-slate-600">Upload the upper video or let AI generate both lanes. Pick a campaign subject and relationship preset; NVIDIA plans the two concepts/scripts so the panels can be related, completely different, or directly talk to each other.</p></div>
    {error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <div className="mb-5 grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-xs font-medium text-slate-600">Campaign subject<select aria-label="Campaign subject" value={category} onChange={e=>{setCategory(e.target.value);setPlan(null)}} className="h-11 rounded-xl border px-3 text-sm">{SUBJECTS.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label className="grid gap-1 text-xs font-medium text-slate-600">Split relationship<select aria-label="Split relationship" value={relationship} onChange={e=>{setRelationship(e.target.value);setPlan(null)}} className="h-11 rounded-xl border px-3 text-sm">{RELATIONSHIPS.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><div className="flex items-end"><Button className="w-full" onClick={()=>planBoth()} disabled={planning}>{planning?<><RefreshCcw size={14} className="mr-2 animate-spin"/>Planning both lanes…</>:<><BrainCircuit size={14} className="mr-2"/>Plan both lanes with AI</>}</Button></div></div>
    {plan&&<div className="mb-5 grid gap-3 md:grid-cols-2"><div className="rounded-2xl border border-sky-200 bg-sky-50 p-4"><div className="font-semibold text-sky-950">Upper plan</div><div className="mt-2 text-sm text-slate-800">{plan.upper.mission}</div>{plan.upper.script&&<div className="mt-2 rounded-lg bg-white/70 p-2 text-xs"><strong>Dialogue:</strong> {plan.upper.script}</div>}</div><div className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><div className="font-semibold text-violet-950">Lower plan</div><div className="mt-2 text-sm text-slate-800">{plan.lower.mission}</div>{plan.lower.script&&<div className="mt-2 rounded-lg bg-white/70 p-2 text-xs"><strong>Dialogue:</strong> {plan.lower.script}</div>}</div></div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_410px]"><section className="rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><div className="font-semibold">Live 9:16 composition</div><div className="text-xs text-slate-500">Top {split}% · Bottom {bottomHeight}%</div></div></div><div className="mx-auto aspect-[9/16] w-full max-w-[470px] overflow-hidden rounded-2xl bg-black"><div style={{height:`${split}%`}} className="relative overflow-hidden border-b border-white/20 bg-slate-900">{topPreview?<video src={topPreview} autoPlay muted={topMode==="upload"} loop playsInline controls className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center p-6 text-center text-sm text-slate-300">{topMode==="upload"?"Upload the upper contextual video":"Generate the AI upper lane"}</div>}{plan?.hook&&<div className="absolute inset-x-3 bottom-2 text-center text-lg font-black uppercase text-white [text-shadow:0_2px_5px_rgba(0,0,0,.85)]">{plan.hook}</div>}</div><div style={{height:`${bottomHeight}%`}} className="relative overflow-hidden bg-slate-950">{lowerPreview?<video src={lowerPreview} autoPlay loop playsInline controls className="h-full w-full object-cover"/>:avatarBase64?<img src={`data:image/png;base64,${avatarBase64}`} alt="Lower spokesperson preview" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center p-6 text-center text-sm text-slate-400">Choose a canonical spokesperson or generate a one-off host.</div>}</div></div><label className="mx-auto mt-4 block max-w-[470px] text-xs font-medium text-slate-600">Top video height: {split}%<input type="range" min="25" max="45" value={split} onChange={e=>setSplit(Number(e.target.value))} className="mt-2 w-full"/></label>{lowerJob?.status==="succeeded"&&<div className="mx-auto mt-4 flex max-w-[470px] gap-2"><Button onClick={sendToCalendar} disabled={scheduleState!=="idle"}><CalendarPlus size={15} className="mr-2"/>{scheduleState==="saved"?"Added to Calendar":scheduleState==="saving"?"Adding…":"Send split-screen to Calendar"}</Button>{scheduleState==="saved"&&<Link href="/calendar" className="self-center text-sm font-medium text-violet-700">Review →</Link>}</div>}</section>
      <aside className="grid content-start gap-4"><section className="rounded-2xl border bg-white p-4"><div className="mb-3 font-semibold">1. Upper lane</div><div className="grid grid-cols-2 gap-2"><button onClick={()=>{setTopMode("upload");setPlan(null)}} className={`rounded-xl border p-3 text-sm font-semibold ${topMode==="upload"?"border-violet-400 bg-violet-50":"bg-white"}`}>Upload video</button><button onClick={()=>{setTopMode("ai");setPlan(null)}} className={`rounded-xl border p-3 text-sm font-semibold ${topMode==="ai"?"border-violet-400 bg-violet-50":"bg-white"}`}>AI generate</button></div>{topMode==="upload"?<label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-3 text-sm font-medium"><Upload size={15}/>Choose upper video<input className="hidden" type="file" accept="video/*" onChange={e=>chooseTop(e.target.files?.[0])}/></label>:<label className="mt-3 grid gap-1 text-xs font-medium text-slate-600">Upper AI engine<select aria-label="Upper AI engine" value={upperProvider} onChange={e=>{setUpperProvider(e.target.value as UpperProvider);setPlan(null)}} className="h-10 rounded-xl border px-2 text-sm"><option value="veo">Gemini / Veo · 8s</option><option value="grok">Grok Imagine · up to 15s</option><option value="a2e">A2E router</option></select></label>}</section>
        <section className="rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><UserRound size={16}/>2. Lower spokesperson</div><label className="grid gap-1 text-xs font-medium text-slate-600">Canonical avatar<select aria-label="Canonical lower avatar" value={selectedAvatar} onChange={e=>chooseAvatar(e.target.value)} className="h-10 rounded-xl border px-2 text-sm"><option value="">Choose canonical avatar</option>{avatars.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{selectedAvatarObj&&avatarBase64&&<div className="mt-2 text-xs text-emerald-700">Using campaign-safe image for {selectedAvatarObj.name}.</div>}<div className="my-3 text-center text-[10px] uppercase tracking-wide text-slate-400">or intentionally create a one-off host</div><label className="grid gap-1 text-xs font-medium text-slate-600">NVIDIA portrait model<select value={freshAvatarModel} onChange={e=>setFreshAvatarModel(e.target.value)} className="h-10 rounded-xl border px-2 text-sm"><option value="black-forest-labs/flux.1-schnell">FLUX.1 Schnell</option><option value="black-forest-labs/flux.2-klein-4b">FLUX.2 Klein</option></select></label><label className="mt-2 grid gap-1 text-xs font-medium text-slate-600">One-off host description<textarea rows={3} value={freshAvatarPrompt} onChange={e=>setFreshAvatarPrompt(e.target.value)} className="rounded-xl border p-2 text-sm"/></label><Button variant="secondary" className="mt-2 w-full" onClick={generateFreshAvatar} disabled={generatingAvatar}>{generatingAvatar?<><RefreshCcw size={14} className="mr-2 animate-spin"/>Generating…</>:<><ImagePlus size={14} className="mr-2"/>Generate one-off host</>}</Button></section>
        <section className="rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><Play size={16}/>3. Lower video engine</div><label className="grid gap-1 text-xs font-medium text-slate-600">Provider<select value={lowerProvider} onChange={e=>{setLowerProvider(e.target.value as ProviderId);setPlan(null)}} className="h-10 rounded-xl border px-2 text-sm"><option value="hedra">Hedra Character 3 · 15/30s</option><option value="grok">Grok Imagine · up to 15s</option><option value="veo">Gemini / Veo · 8s</option><option value="a2e">A2E router</option></select></label>{lowerProvider==="hedra"&&<><label className="mt-3 grid gap-1 text-xs font-medium text-slate-600">Duration<select value={durationSeconds} onChange={e=>{setDurationSeconds(Number(e.target.value));setPlan(null)}} className="h-10 rounded-xl border px-2 text-sm"><option value={15}>15 seconds</option><option value={30}>30 seconds</option></select></label><label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-3 text-sm font-medium"><AudioLines size={15}/><span className="min-w-0 flex-1 truncate">{audioName||"Upload Hedra driving audio"}</span><input className="hidden" type="file" accept="audio/*" onChange={e=>chooseAudio(e.target.files?.[0])}/></label></>}<Button className="mt-3 w-full" onClick={generateBoth} disabled={!canGenerateBoth}>{generating?"Starting both lanes…":topMode==="ai"?"Generate upper + lower videos":"Generate lower video"}</Button>{topJob?.status==="failed"&&<div className="mt-2 text-xs text-rose-700">Upper failed: {topJob.error}</div>}{lowerJob?.status==="failed"&&<div className="mt-2 text-xs text-rose-700">Lower failed: {lowerJob.error}</div>}</section></aside>
    </div>
  </main></AppShell></AuthGuard>;
}
