"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import presets from "@/data/campaign-presets.json";
import backgrounds from "@/data/backgrounds.json";
import tones from "@/data/tones.json";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/app-shell";
import { AuthGuard } from "@/components/auth-guard";
import { BrainCircuit, Check, ChevronDown, ChevronUp, RefreshCcw } from "lucide-react";

type Campaign={id:string;name:string;category:string;website?:string|null;mission:string;tone?:string|null;platform?:string|null;avatarId?:string|null;backgroundId?:string|null;planningHorizonDays?:number;contentType?:string;status:string;createdAt:string};
type Avatar={id:string;name:string;status?:string;views?:{front?:{status?:string}};referenceImage?:string|null;wardrobeRegenerationPrompt?:string|null};
type Plan={mission:string;subject:string;script:string;hook:string;caption:string;visualDirection:string;rationale:string};
const HORIZONS=[3,7,14,30] as const;
const FORMATS=[{id:"cinematic",label:"Cinematic campaign"},{id:"ugc",label:"UGC / creator"},{id:"podcast",label:"Podcast / split-screen"},{id:"newsroom",label:"Newsroom"},{id:"direct",label:"Direct-to-camera"}] as const;

export default function CampaignsPage(){
  const[name,setName]=useState("New campaign"),[website,setWebsite]=useState(""),[category,setCategory]=useState(presets[0]?.id||"ugc"),[contentType,setContentType]=useState("cinematic"),[avatarId,setAvatarId]=useState(""),[tone,setTone]=useState(tones[0]||"direct"),[backgroundId,setBackgroundId]=useState(backgrounds[0]?.id||""),[planningHorizonDays,setPlanningHorizonDays]=useState<3|7|14|30>(7),[autoPost,setAutoPost]=useState(false),[campaigns,setCampaigns]=useState<Campaign[]>([]),[avatars,setAvatars]=useState<Avatar[]>([]),[plan,setPlan]=useState<Plan|null>(null),[planning,setPlanning]=useState(false),[busy,setBusy]=useState(false),[advanced,setAdvanced]=useState(false),[missionOverride,setMissionOverride]=useState(""),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState<string|null>(null),[calendarCount,setCalendarCount]=useState(0);
  const selectedAvatar=useMemo(()=>avatars.find(a=>a.id===avatarId),[avatars,avatarId]);
  const load=useCallback(async()=>{const [cr,ar]=await Promise.all([fetch("/api/campaigns",{cache:"no-store"}),fetch("/api/admin/avatars",{cache:"no-store"})]);if(cr.ok){const d=await cr.json();setCampaigns(d.campaigns||[])}if(ar.ok){const d=await ar.json();setAvatars(d.avatars||[])}},[]);
  useEffect(()=>{load()},[load]);
  async function planCampaign(nextCategory=category,nextAvatar=avatarId,nextFormat=contentType){setPlanning(true);setError(null);try{const avatarName=avatars.find(a=>a.id===nextAvatar)?.name||null;const provider=nextFormat==="podcast"||nextFormat==="direct"||nextFormat==="newsroom"?"hedra":"generic";const duration=provider==="hedra"?30:15;const r=await fetch("/api/internal/campaign-plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({category:nextCategory,provider,durationSeconds:duration,avatarName})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setPlan(d.plan);setMissionOverride("")}catch(e){setPlan(null);setError(e instanceof Error?e.message:String(e))}finally{setPlanning(false)}}
  async function createCampaign(){const mission=(missionOverride.trim()||plan?.mission||"").trim();if(!plan&&!mission){setError("Generate the AI campaign plan first.");return}setBusy(true);setError(null);setSaved(null);try{const r=await fetch("/api/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,website,category,contentType,avatarId,tone,backgroundId,mission,platform:"instagram",planningHorizonDays,autoPost})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setSaved(d.campaign.id);setCalendarCount(d.calendarCount||0);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  return <AuthGuard><AppShell><main className="mx-auto max-w-7xl px-4 py-8">
    <div className="mb-6"><h1 className="text-3xl font-semibold tracking-tight">Campaigns</h1><p className="mt-1 max-w-3xl text-slate-600">Choose the campaign, content format, spokesperson and 3/7/14/30-day horizon. AI writes the campaign brief; Calendar becomes the owner review and auto-post queue.</p></div>
    {error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{saved&&<div className="mb-4 flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><Check size={15}/>Campaign saved · {calendarCount} Calendar slot{calendarCount===1?"":"s"} created.</div>}
    <div className="grid gap-6 xl:grid-cols-[2fr_1fr]"><Card title="Campaign Builder" actions={<Button onClick={createCampaign} disabled={busy||planning||!name.trim()||(!plan&&!missionOverride.trim())}>{busy?<><RefreshCcw size={14} className="mr-2 animate-spin"/>Saving…</>:"Create campaign + fill Calendar"}</Button>}>
      <div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Campaign name</span><input value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-xl border px-4 py-3 text-sm"/></label><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Website / landing page (optional)</span><input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://example.com" className="w-full rounded-xl border px-4 py-3 text-sm"/></label>
      <label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Campaign type</span><select aria-label="Campaign type" value={category} onChange={e=>{setCategory(e.target.value);void planCampaign(e.target.value,avatarId,contentType)}} className="w-full rounded-xl border px-4 py-3 text-sm">{presets.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Content format</span><select aria-label="Content format" value={contentType} onChange={e=>{setContentType(e.target.value);void planCampaign(category,avatarId,e.target.value)}} className="w-full rounded-xl border px-4 py-3 text-sm">{FORMATS.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>
      <label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Canonical spokesperson</span><select aria-label="Canonical spokesperson" value={avatarId} onChange={e=>{setAvatarId(e.target.value);void planCampaign(category,e.target.value,contentType)}} className="w-full rounded-xl border px-4 py-3 text-sm"><option value="">AI chooses / no canonical avatar</option>{avatars.map(a=><option key={a.id} value={a.id}>{a.name}{a.views?.front?.status==="ready"?" · canonical front ready":a.wardrobeRegenerationPrompt?" · canonical front required":" · reference available"}</option>)}</select></label><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Fill Calendar for</span><select aria-label="Fill Calendar for" value={planningHorizonDays} onChange={e=>setPlanningHorizonDays(Number(e.target.value) as 3|7|14|30)} className="w-full rounded-xl border px-4 py-3 text-sm">{HORIZONS.map(x=><option key={x} value={x}>{x} days</option>)}</select></label>
      <label className="md:col-span-2 flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={autoPost} onChange={e=>setAutoPost(e.target.checked)}/><span><strong className="text-sm">Auto-post when approved/due</strong><br/><span className="text-xs text-slate-500">Off keeps every generated Calendar item in owner review/manual publish mode.</span></span></label></div>
      <div className="mt-5 rounded-2xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-semibold text-violet-950"><BrainCircuit size={17}/>AI campaign strategy</div><p className="mt-1 text-xs text-violet-800">The selected campaign type and format are the brief. You do not need to write a prompt.</p></div><Button size="sm" variant="secondary" onClick={()=>planCampaign()} disabled={planning}>{planning?<><RefreshCcw size={13} className="mr-1 animate-spin"/>Planning…</>:"Generate / refresh AI plan"}</Button></div>{plan&&<div className="mt-4 grid gap-3 text-sm"><div><div className="text-[10px] font-semibold uppercase text-violet-700">Hook</div><div className="font-semibold">{plan.hook}</div></div><div><div className="text-[10px] font-semibold uppercase text-violet-700">Mission</div><div>{plan.mission}</div></div><div><div className="text-[10px] font-semibold uppercase text-violet-700">Visual / spokesperson direction</div><div>{plan.subject}</div></div><div className="text-xs italic text-violet-800">{plan.rationale}</div></div>}</div>
      <button type="button" onClick={()=>setAdvanced(v=>!v)} className="mt-4 flex w-full items-center justify-between rounded-xl border bg-slate-50 px-4 py-3 text-left text-sm font-semibold text-slate-800"><span>Optional operator overrides</span>{advanced?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>{advanced&&<div className="mt-4 grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Tone</span><select value={tone} onChange={e=>setTone(e.target.value)} className="w-full rounded-xl border px-4 py-3 text-sm">{tones.map(t=><option key={t} value={t}>{t}</option>)}</select></label><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Background</span><select value={backgroundId} onChange={e=>setBackgroundId(e.target.value)} className="w-full rounded-xl border px-4 py-3 text-sm">{backgrounds.map(bg=><option key={bg.id} value={bg.id}>{bg.name}</option>)}</select></label><label className="md:col-span-2 space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Mission override</span><textarea value={missionOverride} onChange={e=>setMissionOverride(e.target.value)} placeholder={plan?.mission||"AI plan appears above"} className="min-h-28 w-full rounded-xl border px-4 py-3 text-sm"/></label></div>}
    </Card><Card title="Calendar behavior"><ul className="list-disc space-y-2 pl-5 text-sm text-slate-800"><li>3 / 7 / 14 / 30-day horizons are explicit operator choices.</li><li>Format is preserved on each planned Calendar item.</li><li>Generated media attaches itself to Calendar review automatically.</li><li>Owner can edit, approve, post now, or enable auto-post.</li></ul></Card></div>
    <div className="mt-6"><Card title="Saved campaigns"><div className="grid gap-2">{campaigns.map(c=><div key={c.id} className="rounded-xl border bg-white p-3"><div className="font-medium">{c.name}</div><div className="text-xs text-slate-500">{c.category} · {c.contentType||"cinematic"} · {c.planningHorizonDays||7} days · {c.status}</div><div className="mt-2 line-clamp-2 text-sm text-slate-600">{c.mission}</div></div>)}{!campaigns.length&&<div className="py-6 text-center text-sm text-slate-500">No saved campaigns yet.</div>}</div></Card></div>
  </main></AppShell></AuthGuard>;
}
