import type { MarketingCategory, MarketingTerm } from "./types.ts";

type RawTerm = readonly [name: string, definition: string, aliases?: readonly string[]];

const section = (category: MarketingCategory, rows: readonly RawTerm[]): MarketingTerm[] =>
  rows.map(([name, definition, aliases = []]) => ({ name, definition, category, aliases: [...aliases] }));

export const marketingTerms: readonly MarketingTerm[] = [
  ...section("advertising-creative", [
    ["Ad creative", "The visual, video, audio, and written material used in an advertisement."],
    ["Video Sales Letter", "A persuasive video that explains an offer and asks for a conversion.", ["VSL"]],
    ["User-Generated Content", "Customer-created content or advertising deliberately styled like it.", ["UGC"]],
    ["Static ad", "A single-image advertisement."],
    ["Carousel ad", "An advertisement containing multiple swipeable cards."],
    ["Display ad", "A banner or visual advertisement shown across websites or apps."],
    ["Native ad", "An advertisement designed to resemble its surrounding editorial content."],
    ["Advertorial", "Editorial-style content that promotes a product."],
    ["Direct-response ad", "An advertisement seeking an immediate, measurable action."],
    ["Brand ad", "Advertising intended primarily to build awareness or perception."],
    ["Performance creative", "Creative optimized using measurable conversion results."],
    ["Creative concept", "The central strategic idea behind an advertisement."],
    ["Creative angle", "The perspective used to present an offer."],
    ["Hook", "The opening element that captures attention."],
    ["Pattern interrupt", "An unexpected element that breaks automatic viewing behavior."],
    ["Thumb-stopper", "A visual or statement intended to stop scrolling."],
    ["Body copy", "The main explanatory or persuasive portion of an advertisement."],
    ["Call to Action", "An instruction telling the audience what to do next.", ["CTA"]],
    ["Headline", "The primary attention-grabbing statement."],
    ["Subheadline", "Supporting text that clarifies or strengthens a headline."],
    ["Primary text", "The main written copy accompanying a social advertisement."],
    ["Overlay text", "Words displayed over an image or video."],
    ["End card", "The final video screen containing the offer, brand, or call to action."],
    ["B-roll", "Supplementary footage shown over narration or dialogue."],
    ["Voice-over", "Spoken narration recorded over visuals."],
    ["Talking-head ad", "An advertisement in which a person speaks directly to camera."],
    ["Testimonial ad", "An advertisement built around a customer's experience."],
    ["Demo ad", "An advertisement showing the product in action."],
    ["Unboxing", "Content showing a product being opened and examined."],
    ["Before-and-after", "A comparison intended to demonstrate transformation."],
    ["Founder story", "Creative centered on why or how the company was created."],
    ["Problem-solution ad", "Creative that introduces a pain point and presents a resolution."],
    ["Mashup", "An advertisement assembled from multiple clips, testimonials, or formats."],
    ["Iteration", "A modified version of an existing creative."],
    ["Variant", "An alternative version used in testing."],
    ["Creative fatigue", "Performance decline caused by repeated exposure to the same creative."],
    ["Creative testing", "Systematically comparing concepts, hooks, copy, or formats."],
    ["Control", "The current best-performing version in an experiment."],
    ["Challenger", "A new version tested against the control."],
    ["A/B test", "A controlled comparison between two versions."],
    ["Multivariate test", "A test involving several changing variables or combinations."],
  ]),
  ...section("offers-conversion", [
    ["Offer", "The complete value exchange presented to a buyer, not merely the product."],
    ["Value proposition", "The principal reason someone should choose the product."],
    ["Unique Selling Proposition", "A differentiated benefit competitors cannot credibly claim in the same way.", ["USP"]],
    ["Unique Value Proposition", "A concise description of the distinctive value delivered.", ["UVP"]],
    ["Core offer", "The main product or service being sold."],
    ["Lead offer", "A low-friction offer designed to begin a customer relationship."],
    ["Tripwire", "An inexpensive introductory purchase that turns a lead into a customer."],
    ["Loss leader", "An unprofitable or low-margin offer used to attract customers."],
    ["Front-end offer", "The initial purchase presented to a customer."],
    ["Back-end offer", "A subsequent, usually higher-value sale."],
    ["Upsell", "An offer to purchase a more expensive or upgraded option."],
    ["Downsell", "A lower-cost alternative shown after the main offer is declined."],
    ["Cross-sell", "A complementary product offered alongside another purchase."],
    ["Order bump", "A small add-on offered during checkout."],
    ["Bundle", "Multiple products sold together."],
    ["Bonus", "Additional value included with the principal offer."],
    ["Guarantee", "A promise that reduces the buyer's perceived risk."],
    ["Risk reversal", "Shifting some purchase risk from the customer to the seller."],
    ["Free trial", "Temporary product access before payment."],
    ["Freemium", "A permanently free basic version with paid upgrades."],
    ["Scarcity", "Limited availability of an offer."],
    ["Urgency", "A legitimate reason to act within a limited period."],
    ["Deadline", "A specific point after which an offer changes or expires."],
    ["Price anchoring", "Presenting a comparison price that influences perception of another price."],
    ["Decoy pricing", "Adding an option primarily to make another option appear more attractive."],
    ["Charm pricing", "Using prices ending in figures such as .99."],
    ["Price framing", "Presenting cost in a psychologically favorable but accurate unit."],
    ["Offer stack", "A presentation of everything included in the offer.", ["Stack"]],
    ["Value equation", "A framework comparing desired outcome and confidence against delay and effort."],
    ["Conversion", "Completion of the desired action."],
    ["Conversion rate", "The percentage of eligible visitors who complete the desired action."],
    ["Conversion Rate Optimization", "Improving pages and journeys to increase conversions.", ["CRO"]],
    ["Friction", "Anything that makes the desired action harder."],
    ["Objection", "A reason someone hesitates or refuses to buy."],
    ["Objection handling", "Addressing concerns such as price, trust, effort, or suitability."],
    ["Micro-conversion", "A smaller action leading toward the principal conversion."],
    ["Macro-conversion", "The main business outcome, such as a purchase."],
  ]),
  ...section("funnels-journeys", [
    ["Marketing funnel", "The stages through which someone progresses from discovery to loyalty."],
    ["Top of Funnel", "Awareness-stage marketing.", ["TOFU"]],
    ["Middle of Funnel", "Consideration and education activity.", ["MOFU"]],
    ["Bottom of Funnel", "Decision and purchase activity.", ["BOFU"]],
    ["Customer journey", "The complete sequence of customer interactions with a brand."],
    ["Touchpoint", "Any individual interaction with a brand."],
    ["Landing page", "A focused page designed for a particular campaign or action."],
    ["Sales page", "A page designed specifically to persuade visitors to purchase."],
    ["Squeeze page", "A page designed primarily to collect contact information."],
    ["Opt-in", "A person's consent to receive communications."],
    ["Lead magnet", "Free value exchanged for contact details."],
    ["Thank-you page", "The page displayed after form submission or purchase."],
    ["Bridge page", "An intermediate page connecting traffic with the eventual offer."],
    ["Presell page", "Content that prepares a visitor for the main sales presentation."],
    ["Checkout", "The purchase-completion process."],
    ["One-page funnel", "A funnel combining persuasion and conversion on one page."],
    ["Webinar funnel", "A journey using a presentation to educate and sell."],
    ["Application funnel", "A journey requiring prospects to apply before purchasing."],
    ["Lead-generation funnel", "A system designed to acquire prospect information."],
    ["Product-led funnel", "A journey in which product use drives acquisition and conversion."],
    ["Evergreen funnel", "An automated funnel that runs continuously."],
    ["Launch funnel", "A time-bound promotional sequence supporting a release."],
    ["Drip campaign", "A scheduled sequence of automated messages."],
    ["Nurture sequence", "Communications that build trust and purchase readiness."],
    ["Abandoned-cart sequence", "Messages intended to recover incomplete purchases."],
    ["Onboarding", "Helping new customers achieve initial value."],
    ["Activation", "The moment a user experiences meaningful product value."],
    ["Retention", "The ability to keep customers active or subscribed."],
    ["Churn", "The rate at which customers stop buying or cancel."],
    ["Reactivation", "Encouraging inactive customers to return."],
  ]),
  ...section("copywriting", [
    ["AIDA", "Attention, Interest, Desire, Action."],
    ["PAS", "Problem, Agitation, Solution."],
    ["BAB", "Before, After, Bridge."],
    ["FAB", "Features, Advantages, Benefits."],
    ["4Ps", "Promise, Picture, Proof, Push."],
    ["QUEST", "Qualify, Understand, Educate, Stimulate, Transition."],
    ["Problem-promise-proof-proposal", "Identify the problem, promise an outcome, prove it, and present the offer."],
    ["Feature", "What the product contains or does."],
    ["Benefit", "What the customer gains from a feature."],
    ["Outcome", "The final result the customer wants."],
    ["Pain point", "A persistent customer problem or frustration."],
    ["Desire", "An outcome the customer strongly wants."],
    ["Awareness level", "How much a prospect understands their problem, solutions, and the product."],
    ["Voice of Customer", "The actual language customers use to describe needs and experiences.", ["VoC"]],
    ["Message-market fit", "The degree to which marketing language resonates with the intended market."],
    ["Big idea", "A compelling central concept that organizes a campaign."],
    ["Mechanism", "The explanation of how a problem occurs or a solution works."],
    ["Unique mechanism", "A distinctive explanation that differentiates the product."],
    ["Open loop", "Information deliberately left incomplete to maintain attention."],
    ["Curiosity gap", "The distance between what someone knows and wants to know."],
    ["Specificity", "Concrete detail that makes communication clearer and more credible."],
    ["Proof", "Evidence supporting a claim."],
    ["Social proof", "Evidence that other people use, trust, or approve of an offer."],
    ["Testimonial", "A customer's endorsement."],
    ["Case study", "A structured account of a customer's problem, intervention, and result."],
    ["Reason why", "A credible explanation supporting a claim or promotion."],
    ["Guarantee copy", "Language that explains a guarantee and reduces perceived risk."],
    ["CTA copy", "Wording used to prompt the next action."],
    ["Microcopy", "Small interface text such as labels, hints, and error messages."],
    ["Tone of voice", "The consistent personality expressed through communication."],
    ["Brand voice", "The broader verbal identity of a brand."],
  ]),
  ...section("consumer-psychology", [
    ["Authority bias", "Greater trust in perceived experts or credible institutions."],
    ["Scarcity effect", "Limited availability can increase perceived value."],
    ["Urgency effect", "Time pressure can accelerate decisions."],
    ["Loss aversion", "Losses tend to feel more significant than equivalent gains."],
    ["Anchoring", "Early information influences later judgments."],
    ["Framing effect", "Presentation changes how identical information is interpreted."],
    ["Decoy effect", "A third option changes preferences between two main options."],
    ["Reciprocity", "Receiving value can create motivation to return value."],
    ["Commitment and consistency", "People prefer actions consistent with prior commitments."],
    ["Liking principle", "People are more persuaded by those they like or identify with."],
    ["Familiarity effect", "Repeated exposure can increase preference."],
    ["Halo effect", "One positive quality influences wider judgments."],
    ["Confirmation bias", "People favor information supporting existing beliefs."],
    ["Availability heuristic", "Easily recalled examples appear more probable or important."],
    ["Bandwagon effect", "Visible popularity can increase adoption."],
    ["Endowment effect", "Ownership can increase perceived value."],
    ["IKEA effect", "People may value outcomes more when they helped create them."],
    ["Choice overload", "Too many options can delay or prevent decisions."],
    ["Default effect", "People often retain preselected choices."],
    ["Present bias", "Immediate rewards are favored over larger future rewards."],
    ["Hyperbolic discounting", "Future value is discounted inconsistently as time changes."],
    ["Peak-end rule", "Experiences are remembered largely by their peak and ending."],
    ["Zeigarnik effect", "Incomplete tasks can remain mentally salient."],
    ["Goal-gradient effect", "Motivation often increases as a person approaches a goal."],
    ["Mere-measurement effect", "Asking about intentions can influence later behavior."],
    ["Mental accounting", "People assign money to subjective categories."],
    ["Sunk-cost effect", "Prior investment can distort continued commitment."],
    ["Contrast effect", "Perception changes according to nearby comparisons."],
    ["Priming", "Earlier exposure can influence later interpretation or behavior."],
    ["Cognitive fluency", "Easier-to-process messages often feel more trustworthy."],
    ["Processing fluency", "Familiar, clear presentation reduces mental effort."],
    ["Identity-based motivation", "People favor behavior consistent with their self-image."],
    ["Status signaling", "Purchases can communicate identity or social position."],
    ["Self-reference effect", "Personally relevant information is remembered more readily."],
    ["Information-gap theory", "Missing knowledge can create curiosity."],
    ["Motivated reasoning", "Desires influence how evidence is evaluated."],
    ["Reactance", "Excessive pressure can create resistance."],
    ["Paradox of choice", "More choice can reduce satisfaction and action."],
    ["Nudge", "A small environmental or presentation change that influences behavior."],
    ["Gamification", "Using progress, rewards, challenges, or competition to drive engagement."],
  ]),
  ...section("strategy-positioning", [
    ["Marketing strategy", "The decisions governing whom to target, what to offer, and how to win."],
    ["Go-to-market strategy", "The plan for bringing a product to its target market.", ["GTM"]],
    ["STP", "Segmentation, Targeting, Positioning."],
    ["Segmentation", "Dividing a market into meaningful groups."],
    ["Target market", "The group a business chooses to serve."],
    ["Target audience", "The people intended to receive a particular message."],
    ["Ideal Customer Profile", "The customer or organization most valuable and suitable.", ["ICP"]],
    ["Buyer persona", "A research-based representation of a customer type."],
    ["Positioning", "Defining how an offer should be understood relative to alternatives."],
    ["Category creation", "Establishing a new market category around a different problem or solution."],
    ["Differentiation", "Creating meaningful reasons to choose one brand over another."],
    ["Competitive advantage", "A valuable capability competitors cannot easily reproduce."],
    ["Moat", "A durable defense against competition."],
    ["Market orientation", "Building decisions around customer and market intelligence."],
    ["Product-market fit", "Strong market demand for a product.", ["PMF"]],
    ["Channel-market fit", "Alignment between an audience and a distribution channel."],
    ["Market penetration", "Selling more existing products within an existing market."],
    ["Market development", "Bringing existing products into new markets."],
    ["Product development", "Creating new products for an existing market."],
    ["Diversification", "Entering new markets with new products."],
    ["Blue-ocean strategy", "Pursuing relatively uncontested demand."],
    ["Red-ocean strategy", "Competing within an established, crowded category."],
    ["SWOT", "Strengths, Weaknesses, Opportunities, Threats."],
    ["PESTLE", "Political, Economic, Social, Technological, Legal, and Environmental analysis."],
    ["Total Addressable Market", "The maximum theoretical demand for a product or service.", ["TAM"]],
    ["Serviceable Available Market", "The portion of total demand a business can serve.", ["SAM"]],
    ["Serviceable Obtainable Market", "The portion of the serviceable market realistically attainable.", ["SOM (market size)"]],
    ["Jobs to Be Done", "The progress a customer hires a product to achieve.", ["JTBD"]],
    ["North-star metric", "The principal metric reflecting sustained customer value."],
    ["Objectives and Key Results", "A system connecting qualitative objectives to measurable results.", ["OKR", "OKRs"]],
    ["Key Performance Indicator", "A metric used to track performance against an important objective.", ["KPI", "KPIs"]],
  ]),
  ...section("branding", [
    ["Brand", "The collection of associations people attach to a business or product."],
    ["Brand identity", "Visual and verbal elements used to represent a brand."],
    ["Brand image", "How the market actually perceives a brand."],
    ["Brand equity", "Commercial value created by awareness, trust, and associations."],
    ["Brand awareness", "The degree to which people recognize or recall a brand."],
    ["Brand recognition", "Identifying a brand when shown its cues."],
    ["Brand recall", "Remembering a brand without being shown it."],
    ["Top-of-mind awareness", "Being the first brand recalled in a category."],
    ["Salience", "How readily a brand comes to mind in buying situations."],
    ["Distinctive brand assets", "Recognizable colors, shapes, sounds, characters, or phrases."],
    ["Brand archetype", "A symbolic personality pattern used to guide communication."],
    ["Brand promise", "The experience or value customers should consistently expect."],
    ["Brand purpose", "The reason a brand claims to exist beyond making money."],
    ["Mission", "What an organization currently does and for whom."],
    ["Vision", "The future state an organization wants to create."],
    ["Values", "Principles guiding behavior and decisions."],
    ["Tagline", "A memorable phrase expressing the brand or campaign idea."],
    ["Slogan", "A memorable promotional phrase, often campaign-specific."],
    ["Rebranding", "Deliberately changing brand identity or positioning."],
    ["Brand lift", "Measured improvement in awareness, recall, consideration, or preference."],
    ["Share of voice", "A brand's portion of category advertising or conversation.", ["SOV"]],
    ["Share of market", "A company's portion of category sales.", ["SOM (market share)"]],
    ["Excess share of voice", "Share of voice exceeding share of market.", ["ESOV"]],
  ]),
  ...section("paid-media", [
    ["Impression", "One delivery of an advertisement."],
    ["Reach", "The number of unique people exposed."],
    ["Frequency", "Average number of exposures per reached person."],
    ["Cost per thousand impressions", "Advertising cost per one thousand impressions.", ["CPM"]],
    ["Click-through rate", "Clicks divided by impressions.", ["CTR"]],
    ["Cost per click", "Advertising cost divided by clicks.", ["CPC"]],
    ["Cost per acquisition", "Advertising cost divided by acquired customers or target actions.", ["CPA"]],
    ["Cost per lead", "Advertising cost divided by leads.", ["CPL"]],
    ["Cost per install", "Advertising cost divided by installs.", ["CPI"]],
    ["Cost per video view", "Advertising cost divided by qualifying video views.", ["CPV"]],
    ["Cost per engagement", "Advertising cost divided by qualifying engagements.", ["CPE"]],
    ["Customer acquisition cost", "Total acquisition expense divided by new customers.", ["CAC"]],
    ["Return on ad spend", "Attributed revenue divided by advertising spend.", ["ROAS"]],
    ["Marketing efficiency ratio", "Total revenue divided by total marketing expenditure.", ["MER"]],
    ["Return on investment", "Net return relative to investment.", ["ROI"]],
    ["Average order value", "Revenue divided by orders.", ["AOV"]],
    ["Customer lifetime value", "Expected value generated over a customer relationship.", ["LTV", "CLV"]],
    ["LTV:CAC ratio", "The relationship between customer value and acquisition cost."],
    ["Payback period", "Time required to recover acquisition cost."],
    ["Conversion rate (CVR)", "Conversions divided by eligible visits or interactions.", ["CVR"]],
    ["View-through conversion", "A conversion following exposure without a recorded click."],
    ["Attribution window", "The period during which a conversion may receive campaign credit."],
    ["Incrementality", "Results caused by marketing beyond what would have happened otherwise."],
    ["Lift test", "An experiment measuring incremental impact."],
    ["Holdout group", "A group deliberately excluded from treatment for comparison."],
    ["Attribution", "Assigning conversion credit to marketing interactions."],
    ["Last-click attribution", "Assigning all conversion credit to the final recorded click."],
    ["First-click attribution", "Assigning all conversion credit to the first recorded interaction."],
    ["Multi-touch attribution", "Distributing conversion credit among multiple touchpoints."],
    ["Media-mix modeling", "Statistical estimation of how channels influence outcomes.", ["MMM"]],
    ["Blended CAC", "Total acquisition cost divided by all new customers."],
    ["Contribution margin", "Revenue remaining after variable costs."],
    ["Break-even ROAS", "The ROAS at which advertising creates zero contribution profit."],
    ["Ad set/ad group", "A campaign subdivision controlling audience, placement, budget, or bidding."],
    ["Campaign budget optimization", "Platform-level budget distribution across ad sets.", ["CBO"]],
    ["Learning phase", "The period during which an ad platform gathers data to stabilize delivery."],
    ["Bid strategy", "Rules governing how an advertising platform bids."],
    ["Retargeting", "Advertising to people who previously interacted with a brand."],
    ["Prospecting", "Advertising intended to find new customers."],
    ["Lookalike audience", "New users algorithmically matched to a source audience."],
    ["Audience exclusion", "Preventing specified users from receiving an advertisement."],
  ]),
  ...section("growth-lifecycle", [
    ["Growth marketing", "Experiment-driven work spanning acquisition, activation, retention, and revenue."],
    ["Growth loop", "A system in which outputs generate inputs for continued growth."],
    ["AARRR", "Acquisition, Activation, Retention, Referral, Revenue.", ["Pirate metrics"]],
    ["Virality", "Growth created through user sharing or invitations."],
    ["Viral coefficient", "The average number of new users produced by each existing user."],
    ["Referral program", "Incentives for customers to introduce others."],
    ["Affiliate marketing", "Partners receive compensation for generated outcomes."],
    ["Influencer marketing", "Creators promote products to their audiences."],
    ["Ambassador program", "A longer-term relationship with active brand advocates."],
    ["Product-led growth", "Product experience drives acquisition and expansion.", ["PLG"]],
    ["Sales-led growth", "Salespeople drive acquisition and conversion."],
    ["Community-led growth", "Community participation drives trust and adoption."],
    ["Land and expand", "Acquire a small account footprint and grow it later."],
    ["Expansion revenue", "Revenue from existing customers through upgrades or additional usage."],
    ["Net Revenue Retention", "Recurring revenue retained after churn, contraction, and expansion.", ["NRR"]],
    ["Gross Revenue Retention", "Recurring revenue retained before expansion.", ["GRR"]],
    ["Cohort", "Users grouped by a shared starting period or behavior."],
    ["Cohort analysis", "Comparing how different groups behave over time."],
    ["Retention curve", "A graph showing continued customer activity over time."],
    ["Daily/Weekly/Monthly Active Users", "Counts of active users in daily, weekly, or monthly windows.", ["DAU", "WAU", "MAU", "DAU/WAU/MAU"]],
    ["Stickiness", "The frequency with which active users return, often expressed as DAU/MAU."],
  ]),
  ...section("content-seo-social", [
    ["Content marketing", "Creating useful material to attract and nurture an audience."],
    ["Content pillar", "A major topic supporting a brand's content strategy."],
    ["Content cluster", "Interlinked material covering related searches."],
    ["Pillar page", "A broad authoritative page linking to detailed supporting content."],
    ["Search Engine Optimization", "Improving unpaid search visibility and qualified traffic.", ["SEO"]],
    ["Search Engine Marketing", "Marketing through search engines, often referring to paid search.", ["SEM"]],
    ["Search Engine Results Page", "The results page returned for a search query.", ["SERP"]],
    ["Keyword", "A term or phrase associated with a search query."],
    ["Search intent", "The underlying goal of a search."],
    ["Informational intent", "A search made to learn something."],
    ["Commercial intent", "A search made to evaluate products or providers."],
    ["Transactional intent", "A search made in preparation to act or purchase."],
    ["Navigational intent", "A search made to reach a particular site or page."],
    ["Long-tail keyword", "A more specific, usually lower-volume search phrase."],
    ["Backlink", "A link from another website."],
    ["Domain authority", "A third-party estimate of ranking strength, not an official Google metric."],
    ["Organic traffic", "Unpaid visits from search or other non-paid discovery."],
    ["Technical SEO", "Search improvements involving crawling, indexing, performance, and architecture."],
    ["On-page SEO", "Optimizing page content and HTML elements for search."],
    ["Off-page SEO", "External search signals such as links and mentions."],
    ["E-E-A-T", "Experience, Expertise, Authoritativeness, and Trustworthiness."],
    ["Canonical URL", "The preferred URL representing duplicated or similar content."],
    ["CTR optimization", "Improving titles, descriptions, or creative to attract more clicks."],
    ["Engagement rate", "Interactions relative to followers, impressions, or reach."],
    ["Watch time", "Total time viewers spend watching."],
    ["Retention rate", "The percentage of users or viewers retained through a defined interval."],
    ["Completion rate", "The percentage of viewers reaching the end."],
    ["Organic social", "Unpaid distribution through social platforms."],
    ["Paid social", "Advertising through social platforms."],
    ["Dark post", "A paid social post not ordinarily displayed on an account's public feed."],
    ["Social listening", "Monitoring conversations and sentiment around relevant topics."],
    ["Content repurposing", "Adapting one piece of content into other formats."],
    ["Evergreen content", "Material that remains useful for an extended period."],
    ["Trendjacking", "Connecting content to a current trend or event."],
  ]),
  ...section("email-crm", [
    ["Customer Relationship Management", "The system and practice used to manage customer relationships.", ["CRM"]],
    ["Lead", "A potential customer with identifiable contact information or interest."],
    ["Prospect", "A lead considered reasonably suitable for an offer."],
    ["Subscriber", "Someone who has opted into communications."],
    ["Marketing Qualified Lead", "A lead meeting marketing-defined fit or engagement criteria.", ["MQL"]],
    ["Sales Qualified Lead", "A lead accepted as ready for direct sales follow-up.", ["SQL"]],
    ["Product Qualified Lead", "A lead whose product usage indicates buying potential.", ["PQL"]],
    ["Lead scoring", "Ranking leads according to fit and behavior."],
    ["Email segmentation", "Dividing contacts into relevant messaging groups."],
    ["Personalization", "Tailoring communication using recipient data."],
    ["Lifecycle stage", "A contact's current relationship with the business."],
    ["Broadcast", "A one-time message sent to a group."],
    ["Marketing automation", "Messaging or actions triggered by time, behavior, or conditions."],
    ["Email open rate", "The percentage of delivered emails recorded as opened."],
    ["Email click rate", "The percentage of delivered emails that generate a click."],
    ["Click-to-open rate", "Unique clickers divided by recorded openers.", ["CTOR"]],
    ["Email bounce rate", "The percentage of email messages not successfully delivered."],
    ["Hard bounce", "A permanent email delivery failure."],
    ["Soft bounce", "A temporary email delivery failure."],
    ["Unsubscribe rate", "The percentage of recipients who opt out."],
    ["Deliverability", "The ability to reach recipients' inboxes."],
    ["Sender reputation", "The trust assessment applied to a sending domain or IP."],
    ["List hygiene", "Removing invalid, inactive, or risky contacts."],
    ["Double opt-in", "A subscription requiring confirmation."],
    ["Suppression list", "Contacts who must not receive specified messages."],
  ]),
  ...section("research-analytics", [
    ["Market research", "Systematic investigation of customers, competitors, and markets."],
    ["Primary research", "New information collected directly for the present question."],
    ["Secondary research", "Analysis of previously published information."],
    ["Qualitative research", "Non-numerical exploration of motives and experiences."],
    ["Quantitative research", "Numerical measurement and statistical analysis."],
    ["Customer interview", "A structured conversation used to understand behavior and needs."],
    ["Survey", "Standardized questions administered to a sample."],
    ["Focus group", "A moderated discussion involving several participants."],
    ["Usability test", "Observation of people attempting tasks with a product."],
    ["Heatmap", "A visualization of clicks, movement, or attention."],
    ["Session recording", "A recorded representation of website interactions."],
    ["Funnel analysis", "Measurement of movement and drop-off between steps."],
    ["Drop-off", "Users leaving before completing the next step."],
    ["Analytics event", "A tracked user action."],
    ["UTM parameters", "URL tags identifying source, medium, campaign, term, or content."],
    ["Traffic source", "The identifiable origin of a visit."],
    ["Traffic medium", "The broad delivery method, such as email or paid search."],
    ["Direct traffic", "Visits lacking a reliably identified referring source."],
    ["Analytics bounce rate", "The proportion of sessions failing an analytics platform's engagement rule."],
    ["Statistical significance", "Evidence that an observed result is unlikely under a stated null hypothesis."],
    ["Confidence interval", "A range expressing uncertainty around an estimate."],
    ["Sample size", "The number of observations included."],
    ["False positive", "Concluding that an effect exists when it does not."],
    ["Novelty effect", "Temporary behavior caused by something being new."],
    ["Survivorship bias", "Studying visible successes while ignoring failures."],
    ["Vanity metric", "A flattering measurement with little decision-making value."],
    ["Leading indicator", "A measure that tends to change before the final result."],
    ["Lagging indicator", "A measure recording results after they occur."],
  ]),
  ...section("strategic-shorthand", [
    ["Business to Business", "A business model selling to organizations.", ["B2B"]],
    ["Business to Consumer", "A business model selling to individual consumers.", ["B2C"]],
    ["Direct to Consumer", "A brand selling directly to consumers without traditional retail intermediaries.", ["DTC", "D2C"]],
    ["Business to Government", "A business model selling to government entities.", ["B2G"]],
    ["Software as a Service", "Software delivered as an ongoing hosted service.", ["SaaS"]],
    ["E-commerce", "Selling through digital storefronts."],
    ["Omnichannel", "A coordinated customer experience across channels."],
    ["Multichannel", "Using multiple channels that may operate independently."],
    ["Above the line", "Broad-reach mass marketing.", ["ATL"]],
    ["Below the line", "Targeted, directly measurable promotion.", ["BTL"]],
    ["Through the line", "Coordinating broad and targeted marketing.", ["TTL"]],
    ["Pay Per Click", "Advertising in which clicks are a principal billing or optimization event.", ["PPC"]],
    ["PPC campaign", "A paid campaign charged or optimized around clicks."],
    ["Request for Proposal", "A document inviting vendors to propose a solution and price.", ["RFP"]],
    ["Statement of Work", "A document defining scope, deliverables, responsibilities, and terms.", ["SOW"]],
    ["Proof of Concept", "A small implementation used to test feasibility.", ["POC"]],
    ["Minimum Viable Product", "The smallest product capable of testing a value hypothesis.", ["MVP"]],
    ["Minimum Order Quantity", "The smallest order a supplier or seller will accept.", ["MOQ"]],
    ["Manufacturer's Suggested Retail Price", "The retail price recommended by a manufacturer.", ["MSRP"]],
    ["Minimum Advertised Price", "The lowest price a reseller may publicly advertise under an agreement.", ["MAP pricing"]],
    ["Stock Keeping Unit", "An identifier used to track a distinct sellable item.", ["SKU"]],
    ["Monthly Recurring Revenue", "Normalized recurring revenue for one month.", ["MRR"]],
    ["Annual Recurring Revenue", "Normalized recurring revenue for one year.", ["ARR"]],
    ["Average Revenue Per User", "Revenue divided by users or accounts in a period.", ["ARPU"]],
    ["Annual Contract Value", "The annualized value of a customer contract.", ["ACV"]],
    ["Gross Merchandise Value", "The total value of merchandise transacted before deductions.", ["GMV"]],
    ["Net Promoter Score", "A loyalty measure based on likelihood-to-recommend responses.", ["NPS"]],
    ["Customer Satisfaction Score", "A direct rating of customer satisfaction.", ["CSAT"]],
    ["Customer Effort Score", "A rating of how much effort a customer expended.", ["CES"]],
  ]),
];

export const categoryOrder: readonly MarketingCategory[] = [
  "advertising-creative",
  "offers-conversion",
  "funnels-journeys",
  "copywriting",
  "consumer-psychology",
  "strategy-positioning",
  "branding",
  "paid-media",
  "growth-lifecycle",
  "content-seo-social",
  "email-crm",
  "research-analytics",
  "strategic-shorthand",
];
